### ISSUE TITLE
Keyboard Layout is not saved after Install

### ISSUE THREAD

**Issue by henfri** [rockstor/rockstor-core#1102] opened 2016-01-16 11:31 UTC
Hello,

although selecting "de" keyboard layout during the installer, after starting Rockstor, the "us" keyboard layout is selected and the layout must be manually changed.

There are other users having this issue in the forum.

Greetings,
Hendrik

**Comment by phillxnet** [comment] 2016-01-16 12:18
@henfri Thanks for opening his issue, I'm linking to the forum thread mentioned for future convenience.

Could the following forum thread be updated on development with this issue:-
http://forum.rockstor.com/t/a-couple-of-observations-regarding-installation/863

**Comment by fbastok** [comment] 2017-08-23 08:09
The issue is still there as of today, using the latest version

**Comment by Hooverdan96** [comment] 2023-12-15 23:31
Does this problem still exist? The installer has undergone some changes, as well as the underlying platform has been changed from CentOS to OpenSUSE. Personally, I have not found a problem moving from the default `gb` to `us`, but I haven't tried any other combos recently either. If we agree that this doesn't exist as an issue anymore, we should close this.

**Closed** 2023-12-16 13:01 UTC
