### ISSUE TITLE
Exception: Exception while running command(['/usr/bin/hostnamectl', '--static']): [Errno 24] Too many open files

### ISSUE THREAD

**Issue by dohrayme** [rockstor/rockstor-core#2020] opened 2019-02-24 12:46 UTC
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/appliances.py", line 41, in get_queryset
    self._update_hostname()
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/appliances.py", line 48, in _update_hostname
    cur_hostname = gethostname()
  File "/opt/rockstor/src/rockstor/system/osi.py", line 779, in gethostname
    o, e, rc = run_command([HOSTNAMECTL, '--static'])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 113, in run_command
    'Exception while running command({}): {}'.format(cmd, e))
Exception: Exception while running command(['/usr/bin/hostnamectl', '--static']): [Errno 24] Too many open files

**Comment by dohrayme** [comment] 2019-02-24 13:01
cat /proc/sys/fs/file-max
651676
ulimit -Hn
4096
ulimit -Sn
1024

**Comment by phillxnet** [comment] 2019-02-24 13:18
@dohrayme Thanks for the report and investigative info. But this issue looks very much like the following we already have open, ie Too many open files issue essentially:

If you could please contribute your info to that issue so we can close this as:

Duplicate of #1656

"[BUGS] Default ulimit setting too low"

Not as nicely named as this but has more info and research into this ongoing issue.

Thanks again for taking the time and effort and do please copy over your finding into that issue so we can keep all relevant info in the one issue and maintain attribution.

**Comment by dohrayme** [comment] 2019-02-24 13:42
Thats great - rather concerning that the parent ticket has been open since 2017 though.

I didn't see a workaround mentioned - currently the Rockstor UI is pretty much unusable.

**Comment by phillxnet** [comment] 2019-02-24 14:03
Once we find the origin for sure we can fix. Take a look at the linked forum thread and the proposed pull request that @MFlyer commented on as I think that was considered a work around.

> currently the Rockstor UI is pretty much unusable.

with a 'too many open files' state the entire system will be compromised. It's a serious issue but one I suspect is only related to AFP use and given netatalk is suspected un-maintained and apple moving to cifs / smb, I think we are considering dropping AFP in line with other NAS systems. We just need to get our samba up to date enough to allow Time Capsule backups via samba.

I suspect the origin is with our treatment of the AFP service (netatalk) also. But we just don't have that many AFP users, possibly down to this issue also. Please contribute where you can on this as it would be great to get to the bottom of it. I have never seen this myself however but then I don't use AFP and am keen on removing it entirely anyway: once we move to carrying a newer samba and adding Web-UI elements to allow for it's Time Machine config use. See:
SMB Time Machine support #1910
If Apple themselves are moving away from AFP, and netatalk is showing it's age we are best to simply drop it, as per openmediavault. Simplifying our interface options and reducing the code we have to maintain.

**Comment by phillxnet** [comment] 2019-02-24 14:11
@dohrayme Please consider joining our forum. It may be that further contribution to the sighted thread may yield more interest in getting this sorted.
reproducing link from cited duplicate issue for convenience:
https://forum.rockstor.com/t/web-ui-errors-too-many-open-files-while-runing-a-balance/3689
and
https://forum.rockstor.com/t/error-24-too-many-open-files-causes-scheduled-scrub-job-to-fail-and-prevents-login-to-web-ui/3649
There are a couple more references also in the duplicate issue cited.

**Closed** 2024-10-25 11:58 UTC
