### ISSUE TITLE
Importing an unlabeled btrfs RAID5 pool fails

### ISSUE THREAD

**Issue by AngeleToR** [rockstor/rockstor-core#1342] opened 2016-06-09 10:41 UTC
Yesterday I found a minor bug when trying to import a btrfs RAID5 5 disk array into my new system. Another similar array with a label in it worked flawlessly, but the unlabeled one got succesfully imported, mounted and even displayed for a seconds, then dissapeared from the GUI but remained mounted under /mnt2/none (none is how it got temporaly labeled).

Just going to a shell, manually unmounting it, setting a label and re-importing from the GUI did the trick and made it work. As I said, minor annoyance and we all should label our filesystems after all, don't we??? 😆 

It happened on latest stable, 3.8.13 fresh install

**Comment by phillxnet** [comment] 2016-06-10 09:15
@AngeleToR This is a great find; thanks for reporting.
Linking to your forum thread to keep the two tied together.

Please update the following forum thread (by the same author) with any significant development on this issue:- https://forum.rockstor.com/t/importing-an-unlabeled-btrfs-raid5-volume-pool-fails/1590

This issue is caused by the import mechanism doing it's job as expected, the momentary appearance of the pool as evidence, but because the background periodic _update_disk_state() mechanism depends on labels to do it's thing it then fails to deal with the 'None' label condition.

My thoughts on this are that we have some pending changes in this area so I think it would be best to get these out of the way first before looking to this issue, especially now you have provided the work around (Thanks) but maybe after the commits associated with #1320 have been finalised, reviewed, and committed (if appropriate), we could fix this by enhancing the import mechanism to either auto label a pool if it is found to be un-labelled or prompt the use for a label when this circumstance is found. Just my quick thoughts on the matter.

**Comment by AngeleToR** [comment] 2016-10-28 16:45
Sorry for not updating the thread, I though I already did... Anyway, as Phillxnet just pointed out, naming the pool just fixed the issue. Tha fail came from a previous Ubuntu setup, where I could create and use the array unnamed and so I tried to import it that way... triggering the error...

**Comment by phillxnet** [comment] 2016-10-28 17:15
@AngeleToR Thanks for the update, but I think this issue could be re-opened as it still exists, I was simply referencing your fine find on the work around you presented here. Not strictly an issue with intra-Rockstor pools and a niggle as you say but still it's not elegant behaviour and imports of whole disk btrfs should fall within our remit. Your call.

**Comment by AngeleToR** [comment] 2016-10-28 17:21
Oh well, I misunderstood it then... Pools should be named, as we all know, to avoid mistakes like deleting the one you don't want to and so. So it's not a bug in the strict sense, more like a 'nice to have' feature or, as you said, a non elegant behaviour of the interface, but it's OK for me to reopen it so it can be nicely closed once you fix it in the GUI.
Regards

**Closed** 2017-03-29 01:06 UTC
Labels: bug
