### ISSUE TITLE
Docs for Plex-Rockon need update

### ISSUE THREAD

**Issue by henfri** [rockstor/rockstor-core#1239] opened 2016-04-03 14:40 UTC
Hello,

with the new plex-rockon, the Documentation is outdated. The parameters GID, UID and Version are not explained.

Greetings,
Hendrik

**Comment by phillxnet** [comment] 2016-04-03 18:38
@henfri I am currently working on this very thing but it's over on the doc repo ie:
https://github.com/rockstor/rockstor-doc
and the issue in question is https://github.com/rockstor/rockstor-doc/issues/135
It should be ready for review in a few hours.

**Comment by phillxnet** [comment] 2016-04-03 18:43
@henfri I suggest we close this issue as a duplicate, are you OK with that.

**Comment by henfri** [comment] 2016-04-03 19:40
I am sorry. I searched the forum only.
Thanks for working on it!

**Comment by phillxnet** [comment] 2016-04-03 20:42
@henfri Thanks, it was about time. Are you game to close this issue as a duplicate of:
https://github.com/rockstor/rockstor-doc/issues/135
Cheers. And thanks for opening in the first place. All dandy except it needed to be in the docs repo.
Funny how our timing coincided.

**Comment by FroggyFlox** [comment] 2023-12-19 19:56
Closing as an issue was appropriately created in the correct repository (see message above).

**Closed by FroggyFlox** 2023-12-19 19:56 UTC
