### ISSUE TITLE
Web-UI can't login

### ISSUE THREAD

**Issue by PMontroy** [rockstor/rockstor-core#2774] opened 2023-12-28 14:51 UTC
Hi,

I am a newbie to this as I just setup my Frist Rockstor server lastnight and got Plex installed.
I loged out and the next day I am unable to login to the Web-UI no matter what user and password I use.
I can connect to the server as root using putty and run commands.
I there a work around or fix to this issue?

Thanks,

Paul

**Comment by Hooverdan96** [comment] 2023-12-28 19:34
@PMontroy, these types of issues are best discussed in the Rockstor forum here:

https://forum.rockstor.com/

Would you mind opening a topic over there, as I suspect it's not a functional bug (if it turns out to be, we can continue over here to get it addressed)?

Also, it would be good to then provide some information which version of Rockstor you have installed (I assume it's the 4.x, but want to make sure).

**Comment by phillxnet** [comment] 2023-12-29 14:14
Closing as we have no reproducer: linking to @PMontroy forum thread: 

https://forum.rockstor.com/t/can-no-longer-login-to-web-ui/9186

**Closed by phillxnet** 2023-12-29 14:14 UTC
