### ISSUE TITLE
task history: columns of start/end time are inverted

### ISSUE THREAD

**Issue by jakieu** [rockstor/rockstor-core#1129] opened 2016-01-26 19:52 UTC
The columns of start time and end time are inverted in the task history.
![scrub_log](https://cloud.githubusercontent.com/assets/8632220/12592869/9eea640c-c46e-11e5-8b40-6d35d8171160.png)

**Comment by phillxnet** [comment] 2016-01-29 15:25
@Mchakravartula Could this be a duplicate of #968 
ie note the comment on 20th October.

**Comment by Mchakravartula** [comment] 2016-02-01 14:35
@phillxnet  Yep, this is duplicate of #968

**Comment by schakrava** [comment] 2016-02-08 23:28
Fixed by #1156

**Closed by schakrava** 2016-02-08 23:28 UTC
