### ISSUE TITLE
Rockon with multiple containers requires same env variables for all containers

### ISSUE THREAD

**Issue by freaktechnik** [rockstor/rockstor-core#2202] opened 2020-08-15 01:49 UTC
Define a rockon with multiple containers. The two containers require a different set of environment variables to be set by the user. Installing the rockon will fail, due to an env variable that was set in the wizard not existing for one of the containers.

**Comment by FroggyFlox** [comment] 2020-08-15 13:51
Hi @freaktechnik ,

Thanks a lot for your interest in multi-containers rock-ons; it's nice to see there's a lot of interest in this.

Unfortunately, I believe you are highlighted an issue that was previously raised (https://github.com/rockstor/rockstor-core/issues/1588#issue-196222237) and for which a pull-request was submitted (#1688). I personally am very motivated in getting to that one as soon as things settle down on the relaunch, so it's very encouraging to see that this interest is shared by other users. We have now seen multiple users that would have benefited from this being fixed/enabled, so I will definitely get on that once I can.

Sorry for not being able to provide you with a solution right away, unfortunately.

Hope this helps anyway...

**Comment by freaktechnik** [comment] 2020-08-15 13:52
I have found a workaround, which is to have the same set of env vars for all containers. Curiously this repeats the fields in the env var input, but will only show them once in the end table.

**Comment by freaktechnik** [comment] 2020-08-15 20:04
This is what the resulting definition looks like btw: https://github.com/freaktechnik/rockons/blob/master/matrix-synapse.json

In theory only matrix-synapse needs GID and UID and only the postgres container needs the pw (though the pw bootstrapping doesn't seem to have worked in the first place)

**Comment by FroggyFlox** [comment] 2020-08-16 11:56
That's a great candidate for a rock-on, especially given its reputation as being a little complex to setup!
Let's hope we'll be able to fix that underlying limitation relatively soon.

Thanks!

**Comment by freaktechnik** [comment] 2020-08-16 11:59
Yeah, I've noted some of the caveats with the rockon I ended up with in the README. Essentially the TURN server can't STUN, and I didn't manage to get Element as part of the setup. I've now simply used the Element app for Nextcloud to self-host Element. I guess an even more advanced package would also include jitsi, though I think that could be a separate rockon that you can just integrate at rockon setup time. Either way, seeing a more streamlined version would definitively be great!

**Comment by freaktechnik** [comment] 2021-11-17 21:03
This also appears to apply to `devices`.

**Comment by phillxnet** [comment] 2024-08-12 09:42
Closing as:
Duplicate of #1588

"Rockons: Invalid environment variabled" #1588

As per @FroggyFlox comment https://github.com/rockstor/rockstor-core/issues/2202#issuecomment-674398758

**Closed by phillxnet** 2024-08-12 09:42 UTC
