### ISSUE TITLE
Cannot start samba. Cannot start bootstrap

### ISSUE THREAD

**Issue by conrad82** [rockstor/rockstor-core#1181] opened 2016-02-21 14:19 UTC
Hi,

I am unable to run samba. It worked right after install, but it does not work any more. I believe it is a similar problem I have seen in other issues. Help?

Rockstor was installed using the ISO on the web page. When samba stopped working the first time, I tried reinstalling rockstor again (using a new download and usb install disk of the ISO on web page). Samba worked for a few days, presumably to a reboot or after activating auto-update.

I have tried to install the test version, but it did not change anything.

This is the error message I get from the shell:

`[root@nas_sn17 ~]# /opt/rockstor/bin/bootstrap
BTRFS device scan complete
Exception occured while bootstrapping. This could be because rockstor.service is still starting up. will wait 2 seconds and try again. Exception: Internal Server Error: No JSON object could be decoded
Exception occured while bootstrapping. This could be because rockstor.service is still starting up. will wait 2 seconds and try again. Exception: Internal Server Error: No JSON object could be decoded`

running systemctl:
`[root@nas_sn17 ~]# systemctl status rockstor-bootstrap -l
● rockstor-bootstrap.service - Rockstor bootstrapping tasks
   Loaded: loaded (/etc/systemd/system/rockstor-bootstrap.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2016-02-21 09:20:13 CET; 5h 55min ago
  Process: 22819 ExecStart=/opt/rockstor/bin/bootstrap (code=exited, status=1/FAILURE)
 Main PID: 22819 (code=exited, status=1/FAILURE)`

`Feb 21 09:20:13 nas_sn17 bootstrap[22819]: Exception occured while bootstrapping. This could be because rockstor.service is still starting up. will wait 2 seconds and try again. Exception: Internal Server Error: No JSON object could be decoded
Feb 21 09:20:13 nas_sn17 bootstrap[22819]: Exception occured while bootstrapping. This could be because rockstor.service is still starting up. will wait 2 seconds and try again. Exception: Internal Server Error: No JSON object could be decoded
Feb 21 09:20:13 nas_sn17 bootstrap[22819]: Exception occured while bootstrapping. This could be because rockstor.service is still starting up. will wait 2 seconds and try again. Exception: Internal Server Error: No JSON object could be decoded
Feb 21 09:20:13 nas_sn17 bootstrap[22819]: Exception occured while bootstrapping. This could be because rockstor.service is still starting up. will wait 2 seconds and try again. Exception: Internal Server Error: No JSON object could be decoded
Feb 21 09:20:13 nas_sn17 bootstrap[22819]: Exception occured while bootstrapping. This could be because rockstor.service is still starting up. will wait 2 seconds and try again. Exception: Internal Server Error: No JSON object could be decoded
Feb 21 09:20:13 nas_sn17 bootstrap[22819]: Max attempts(15) reached. Connection errors persist. Failed to bootstrap. Error: Internal Server Error: No JSON object could be decoded
Feb 21 09:20:13 nas_sn17 systemd[1]: rockstor-bootstrap.service: main process exited, code=exited, status=1/FAILURE
Feb 21 09:20:13 nas_sn17 systemd[1]: Failed to start Rockstor bootstrapping tasks.
Feb 21 09:20:13 nas_sn17 systemd[1]: Unit rockstor-bootstrap.service entered failed state.
Feb 21 09:20:13 nas_sn17 systemd[1]: rockstor-bootstrap.service failed.`

I tried this after over 1 day of uptime, so it is not a bootup problem (which I have seen in other issues).

`[root@nas_sn17 ~]# uptime
 15:16:23 up 1 day,  6:47,  1 user,  load average: 0.18, 0.13, 0.08`

**Comment by schakrava** [comment] 2016-02-29 22:34
Thanks for reporting this issue. Random question, but may be related. Do you still have this issue? If so, how does your Storage -> Disks screen look like? Are there any entries with long disk names with recycle bin icon next to their name? A screenshot would be great if possible.

**Comment by conrad82** [comment] 2016-03-01 19:11
Hi,

thank you for your reply!

yes I still have the issue and can confirm it happens after first reboot. I tried reinstalling and rebooting to confirm. I have now installed Rockstor again and not rebooted so at the time samba is working

You are right, there is one with a long name. There is no recycle bin icon. However, I have not rebooted yet if that is relevant.

In case it is relevant, I originally had 3 hdd's for the pool. 
I then added a new one (sdb) and removed two older ones after the balancing completed.

Let me know if there is some more information i could provide that could help resolving this issue

![image](https://cloud.githubusercontent.com/assets/17353007/13438228/6a0c8428-dfe8-11e5-9d96-358d75b0621f.png)

**Comment by schakrava** [comment] 2016-03-28 14:00
Sorry for the late reply, but any chance you could e-mail the logs (/opt/rockstor/var/log) to support@rockstor.com?

**Comment by conrad82** [comment] 2016-04-02 06:40
Hi,

error logs have been sent to support@rockstor.com. Apr 2, 2016, 8:38 AM (Central European Time)

**Comment by schakrava** [comment] 2016-04-03 16:18
Hello @conrad82 . The logs were very helpful. The bug is being triggered because of usage calculation for a phantom share. Fortunately, it's been fixed in 0ce536ff0e32b7a545619d064b8e8bbaad9c8356 already. Looks like you are running stable updates, so you'll get the fix with next update. We are planning to release it in next 1-2 weeks.

**Comment by conrad82** [comment] 2016-04-07 19:37
Glad to hear it! I will let you know how -13 works out when it arrives

**Comment by peterdenhaan** [comment] 2016-04-11 13:28
@schakrava wanted to add that I just had a problem with identical presentation to this one, and quickly patching in 0ce536ff0e32b7a545619d064b8e8bbaad9c8356 did indeed fix it.

In my case, the root cause was `rockstor_rockstor` running out of metadata space. I'm running quite a few docker containers and their volumes are probably making  heavy metadata demands. The pool wouldn't even rebalance for lack of space. I got out of that corner by temporarily adding a flash drive to the pool. Once the filesystem was working again, I ran into the above error. I suspect some of the qgroup data got out of whack.

**Comment by schakrava** [comment] 2016-04-20 14:33
Fixed by #1234

**Closed by schakrava** 2016-04-20 14:33 UTC
Labels: bug

**Comment by conrad82** [comment] 2016-04-22 17:47
3.8-13 indeed seems to have fixed the problem! 

Good job!

**Comment by holmesb** [comment] 2016-05-15 17:33
I'm having the issue with 3.8-13, so it isn't closed.
![image](https://cloud.githubusercontent.com/assets/5072156/15275668/a8de7a14-1ac9-11e6-82f3-31d4df5a1fb6.png)
I have emailed my logs to support@rockstor.com

**Comment by holmesb** [comment] 2016-05-21 22:39
When attempting to start the bootstrap service, rockstor logs showed a "Not found" error when running command btrfs qgroup show /mnt2/rockstor_rockstor
So I ran command btrfs quota enable /mnt2/rockstor_rockstor
Now samba and the rockstor-bootstrap.service start successfully! :-)
