### ISSUE TITLE
HP ProLiant - doesn't show new drives

### ISSUE THREAD

**Issue by tomvancutsem** [rockstor/rockstor-core#1715] opened 2017-05-22 15:21 UTC
Hello,

I installed Rockstor with only my ssd installed. Later I added 2x WD red 3TB. The wd's don't show up in the disks menu. Restarting doesn't help. Clicking Rescan gives an error:

value too long for type character varying(256)

            Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 320, in post
    return self._update_disk_state()
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 268, in _update_disk_state
    dob.save()
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(256)

**Comment by tomvancutsem** [comment] 2017-05-22 15:23
**
Hello,
I install Rockstor with only my ssd installed. Later I added 2x WD red 3TB. The drives don't show up in the disks menu. Restarting doesn't help. Clicking Rescan gives an error:

**Comment by phillxnet** [comment] 2017-05-22 17:54
@tomvancutsem Thanks for opening this issue and the clear description. It is a know bug that can happen when dealing with prior use drives containing many partitions. Please see #1709 for details and current limitations. You work around for the time being is to wipe the existing partitions from your data drives (which will of course remove all their data). Please also see forum post:
https://forum.rockstor.com/t/drive-discovery/3053

This is my fault I'm afraid due to lack of foresight on the changes I have recently made to the disk role system and their interaction with prior use disks.

Now that I have referenced the issue that this represents a duplicate of, are you happy to close this issue as such ie "Closing as duplicate of #1709 " that way we can keep all relevant notes under the one issue.

Thanks.

**Comment by tomvancutsem** [comment] 2017-05-23 09:00
Ok, thank you!
Whiping the drive fixed it.

Love Rockstor, keep up the good work ;)

2017-05-22 19:54 GMT+02:00 Philip Guyton <notifications@github.com>:

**Comment by phillxnet** [comment] 2017-05-23 09:55
@tomvancutsem Chuffed it worked for you and thanks for the update.
Gad your enjoying Rockstor and thanks for the  team encouragement.

As your report seems to have validated the premise of this being a duplicate: could you now close this issue as "Closing as duplicate of #1709" if that is also your assessment? Cheers.

**Closed** 2017-05-23 10:44 UTC

**Comment by phillxnet** [comment] 2017-05-31 16:37
@tomvancutsem Just a notification that the fix for the issue that you reported here has now been released in version 3.9.0-8 by way of a 4 fold lengthening of the problematic field.
Thanks again for reporting and confirming the work around.
The fix was via pr #1717
