### ISSUE TITLE
Consider supporting partitions and not just whole drives.

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#509] opened 2014-10-27 17:03 UTC
Some users asked if they can use partitions instead of whole drives while creating pools.

**Comment by utting** [comment] 2015-01-28 22:56
Yes, this would be very useful.
It would also allow us to create a Raid1 pool across two drives of different sizes (by creating a same-size partition on each of those drives).
Thanks.

**Comment by phillxnet** [comment] 2015-06-03 15:55
@utting I think btrfs can use two differently sized disks in data raid1 mode but as is probably your point it will only fill each disk up to the capacity of the smaller of the two.  So "whole disks only" doesn't prevent use of raid1 but may be wasteful. Btrfs can however use raid1 on 3 devices and in data raid1 I think it will maintain 2 copies of the data across 2 of the 3 devices.  This is from kernel 3.0 onwards I think.  It doesn't have the same limitation as zfs where the disks / partitions have to be exactly the same size ie  fails on MBs difference between manufacturers or even versions of the same model.  This is one reason why by default FreeNAS puts a 1GB swap on every drive to allow wiggle room when a replacement drive is very slightly larger or smaller than the existing ones.  Although I have had to manually partition away 4.3GB difference between manufacturers of 160GB drives in the past (for FreeNAS ZFS this was).

btrfs reference https://btrfs.wiki.kernel.org/index.php/FAQ#btrfs "RAID-1 is defined currently as "2 copies of all the data on different devices""

https://stackoverflow.com/questions/23620964/btrfs-raid1-with-multiple-devices/23621137#23621137
"Btrfs distributes the data (and its RAID 1 copies) block-wise, thus deals very well with hard disks of different size." Jens Erat

I don't think given the "btrfs only" nature of Rockstor the complexity introduced by partitioning makes sense.  Given the above referenced btrfs flexibility I think there is essentially no need for dealing with partitions and a compromise at this level could interfere with ease / complexity of use for no benefit. It would also make for a larger problem space to debug / stabilise, ie the varying partition tables and their potential non compliance to standards (whos standards as well) or corruption there in etc.

So I vote for whole disk use only in pools created via the Web GUI and no need for a Web GUI partitioning tool in Rockstor.  Some unfamiliar with btrfs might go straight there out of habit and loose some of the convenience / simplicity that we inherit otherwise.

Just finding my feet here so have probably got the wrong end of the stick.

**Comment by iFloris** [comment] 2015-06-03 16:22
It seems to me that @phillxnet has a good point.

**Comment by schakrava** [comment] 2015-06-04 16:01
@iFloris it seems to be that @phillxnet often does.

I've been of the same opinion about unnecessary complexity that comes with supporting partitions. That is why we don't support it as of now. But with all features, the community factor is pretty important and there were a couple of users in the last several months that asked for this feature. And that prompted me to create this issue. It's really helpful have everyone's feedback. Thanks!

**Comment by iFloris** [comment] 2015-06-04 16:08
@schakrava Thanks, I can understand how it can be difficult sometimes to balance community wants/needs with Rockstor's company vision. Perhaps some kind of advanced settings tab somewhere to tuck away highly specialised functions like these could be a middle ground?

**Comment by schakrava** [comment] 2015-08-27 18:16
Another forum topic in support of this feature: http://forum.rockstor.com/t/possible-to-use-partitions-not-whole-devices-for-btfs/396

**Comment by phillxnet** [comment] 2017-03-17 17:36
@schakrava Given the merged status of pr  #1622 "enhance disk role/management subsystem" for issue #1494 I think we can now close this issue as btrfs within partition is now possible, with the caveat that we only deal with one partition per device: a compromise intended to add the minimum complexity both internally and to the user experience, ie we maintain the 'one drive one use' type remit.

Although these changes do allow for btrfs in partition it is still strongly encouraged (via UI text hints and the disk role configuration page instructions) to only use whole disk btrfs unless unavoidable. The main motivation for the indicated changes were to improve flexibility and accommodate more common use cases such as are indicated in #1157 "Support backup to USB devices" which includes import from USB devices. In that use case we are almost always going to encounter partitioned devices (ie as they come from the shop) and are populated prior to import / NAS install) but again this almost 100% of the time only involves a single partition per device.

I still advocate that we do not support a partition management system within the UI, much beyond what we already have, for the reasons already covered and this issue seems not to have that as a focus anyway.

@iFloris The new disk roles page defaults to using the whole disk and tries repeatedly to dissuade the use of btrfs in partition so hopefully we have our 'middle ground' at least in part.

Propose closing as fixed by pr #1622 .

**Comment by phillxnet** [comment] 2019-03-01 12:03
Linking to a related currently pending pr that fixes a recent regression in btrfs in partition function. This Regression was added in pr #1949 commit a608d18 released (3.9.2-32).

I intend to close this issue upon that pr being merged (planned for 3.9.2-49) as this 'beta' capability should then functional again:

"pool resize disk removal unknown internal error and no UI counterpart. Fixes #1722" #2010

**Comment by phillxnet** [comment] 2019-07-09 14:16
Closing as the previously referenced pr:

> "pool resize disk removal unknown internal error and no UI counterpart. Fixes #1722" #2010

has now be merged.

**Closed by phillxnet** 2019-07-09 14:16 UTC
