### ISSUE TITLE
"on rockstor" in the end of afp share name

### ISSUE THREAD

**Issue by fva-dev** [rockstor/rockstor-core#1887] opened 2018-01-29 14:34 UTC
Great job!
But how to remove on rockstor words in the end of afp share. This words is not good for my purposes.

**Comment by phillxnet** [comment] 2018-01-30 10:57
@fva-dev Thanks for the encouragement and feedback but this issue is actually a:

Duplicate of #1347 

I would request that you please comment on that issue and close this one as a duplicate as it makes it easier to judge the relative interest in this features; and collects all relevant info in one place. And now that I have linked that issue, this one should show there anyway but it would also help if you put an additional comment there. Also an indication as to why this is an issue would be good for context.

Cheers.

**Closed** 2018-01-30 13:25 UTC
