### ISSUE TITLE
Mgmt IP is blank

### ISSUE THREAD

**Issue by barnhill** [rockstor/rockstor-core#1686] opened 2017-04-02 16:44 UTC
![nomgmtip](https://cloud.githubusercontent.com/assets/3878158/24589048/b00b5050-1799-11e7-861e-4186c36f15b4.png)

**Comment by barnhill** [comment] 2017-04-02 17:12
version 3.9.0-0

**Comment by MFlyer** [comment] 2017-04-02 18:01
Hi @barnhil,
this is not a bug, probably you just need to "set it" : appliance config page or network page, I don't remember

**Comment by barnhill** [comment] 2017-04-03 16:26
There is no way to set it on the appliance page.  Its a non-editable field.

**Comment by MFlyer** [comment] 2017-04-03 22:02
Uhmm..click on that Mgmt IP, sorry @barnhill I really don't remember where we set it xD

**Comment by barnhill** [comment] 2017-04-04 00:56
Clicking on mgmt ip goes to the same screen to setup an appliance.  The up there says *.  I can't modify that.

**Comment by MFlyer** [comment] 2017-04-04 08:03
Shame on me @barnhill , finally got it!

Rockstor -> Services page -> click on Rockstor service wrench icon and et voilà

![mgmt](https://cloud.githubusercontent.com/assets/17988902/24646866/b5e6af80-191d-11e7-9ea9-4f3930d11a1f.jpg)

Set network interface to your network interface from dropdown list
Important: after this change WebUI should be unavailable for a while

Mirko

**Comment by MFlyer** [comment] 2017-04-06 21:03
Hi @barnhill , any news on this?

**Comment by barnhill** [comment] 2017-04-06 21:35
sorry been sick.  Looks like that fixed it.  A little unintuitive on where to set that but that fixed it.

**Comment by MFlyer** [comment] 2017-04-06 21:38
Thanks @barnhill , can we close this and open a new issue (can you do it? :) ) over Rockstor documentation repository? You're right about not intuitive configuration!

Mirko

**Comment by barnhill** [comment] 2017-04-07 07:23
Sounds good to me

**Closed** 2017-04-07 07:24 UTC
