### ISSUE TITLE
Rockstor no longer starting and shares are unavailable

### ISSUE THREAD

**Issue by djevo1** [rockstor/rockstor-core#1381] opened 2016-07-07 21:32 UTC
I am receiving this error when attempting to start rockstor. I am unable to access the shares or the webui but can access the cli.

```
Traceback (most recent call last):
  File "/opt/rockstor/bin/initrock", line 44, in <module>
    sys.exit(scripts.initrock.main())
  File "/opt/rockstor/src/rockstor/scripts/initrock.py", line 418, in main
    run_command([PREP_DB, ])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 98, in run_command
    raise CommandException(cmd, out, err, rc)
system.exceptions.CommandException: Error running a command. cmd = ['/opt/rockstor/bin/prep_db']. rc = 1. stdout = ['']. stderr = ['Traceback (most recent call last):', '  File "/opt/rockstor/bin/prep_db", line 44, in <module>', '    sys.exit(scripts.prep_db.main())', '  File "/opt/rockstor/src/rockstor/scripts/prep_db.py", line 63, in main', '    create_setup()', '  File "/opt/rockstor/src/rockstor/scripts/prep_db.py", line 57, in create_setup', '    if len(setup) == 0:', '  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/query.py", line 77, in __len__', '    self._fetch_all()', '  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/query.py", line 857, in _fetch_all', '    self._result_cache = list(self.iterator())', '  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/query.py", line 220, in iterator', '    for row in compiler.results_iter():', '  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/sql/compiler.py", line 713, in results_iter', '    for rows in self.execute_sql(MULTI):', '  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/sql/compiler.py", line 785, in execute_sql', '    cursor = self.connection.cursor()', '  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/backends/__init__.py", line 162, in cursor', '    cursor = util.CursorWrapper(self._cursor(), self)', '  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/backends/__init__.py", line 132, in _cursor', '    self.ensure_connection()', '  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/backends/__init__.py", line 127, in ensure_connection', '    self.connect()', '  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/utils.py", line 99, in __exit__', '    six.reraise(dj_exc_type, dj_exc_value, traceback)', '  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/backends/__init__.py", line 127, in ensure_connection', '    self.connect()', '  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/backends/__init__.py", line 115, in connect', '    self.connection = self.get_new_connection(conn_params)', '  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/backends/postgresql_psycopg2/base.py", line 115, in get_new_connection', '    return Database.connect(**conn_params)', '  File "/opt/rockstor/eggs/psycopg2-2.6-py2.7-linux-x86_64.egg/psycopg2/__init__.py", line 164, in connect', '    conn = _connect(dsn, connection_factory=connection_factory, async=async)', 'django.db.utils.OperationalError: could not connect to server: No such file or directory', '\tIs the server running locally and accepting', '\tconnections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?', '', '']
```

**Comment by phillxnet** [comment] 2016-07-08 08:55
@djevo1 is this on a fresh install or does this issue represent the current status of the system you had attached to a faulty network switch which then experienced several other issues once that network hardware issue was resolved as you detail in the linked issue.
Linking to #1363 just in case as this log snippet is duplicated there in the post made 3 days before this one.

A current sensitive time for Rockstor is during install when a reliable internet connected network is assumed for various package adjustments. Some of these are executed on first boot after install, hence my above question. In the linked post you also requested details of re-install procedure, this I supplied within that issue. You then detail re-installing via yum which is not a fresh install. But as you say in that issue you no longer had Web-UI access which obviously hampers making config backups (another area we could improve upon).

If you have stored no data on the system disk then the referenced re-install and pool / share import methods may be the way to go. But you will loose all other settings of course. Otherwise it's difficult to exactly re-produce the cause of  your indicated issue here as we have no steps that led to it.

Have you for instance installed anything else on this system via the cli as we do have a dependency on an older version of Python due to some other dependencies; network issues at one time or another may have blocked this downgrade and could be causing your current problem.

If this is in fact a continuation of issue #1363 then we are at lease building a history of sorts that may lead to how this came about.  Is there any other contextual information on how you got to the current state indicated in this issue. On top of if it represents the current / latest system state of the other issue you have open (other than the afp share name one of course).

Thanks for helping to identify the weak points of Rockstor and hopefully making it better for everyone.

**Comment by djevo1** [comment] 2016-07-08 10:51
This was the one connected to the faulty switch. I went ahead and completely reinstalled the OS last night using the rockstor image file and imported the pool and share data from the disks. This ended up fixing the issue. I hadn't changed any packages via cli so I dont believe that was the issue. 

---Sent from Boxer | http://getboxer.com

On July 8, 2016 at 4:55:57 AM EDT, Philip Guyton <notifications@github.com> wrote:@djevo1 is this on a fresh install or does this issue represent the current status of the system you had attached to a faulty network switch which then experienced several other issues once that network hardware issue was resolved as you detail in the linked issue. Linking to #1363 just in case as this log snippet is duplicated there in the post made 3 days before this one.  A current sensitive time for Rockstor is during install when a reliable internet connected network is assumed for various package adjustments. Some of these are executed on first boot after install, hence my above question. In the linked post you also requested details of re-install procedure, this I supplied within that issue. You then detail re-installing via yum which is not a fresh install. But as you say in that issue you no longer had Web-UI access which obviously hampers making config backups (another area we could improve upon).  If you have stored no data on the system disk then the referenced re-install and pool / share import methods may be the way to go. But you will loose all other settings of course. Otherwise it's difficult to exactly re-produce the cause of your indicated issue here as we have no steps that led to it.  Have you for instance installed anything else on this system via the cli as we do have a dependency on an older version of Python due to some other dependencies; network issues at one time or another may have blocked this downgrade and could be causing your current problem.  If this is in fact a continuation of issue #1363 then we are at lease building a history of sorts that may lead to how this came about. Is there any other contextual information on how you got to the current state indicated in this issue. On top of if it represents the current / latest system state of the other issue you have open (other than the afp share name one of course).  Thanks for helping to identify the weak points of Rockstor and hopefully making it better for everyone.  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by phillxnet** [comment] 2016-07-08 16:05
@djevo1 Thanks for the update and additional info, I have opened a feature request / enhancement issue influenced by your reported experience here "add cli initiated config backup" #1382 and I believe the existing #787 issue may also make things more robust network wise especially during install and first boot as we move forward.

As this and the associated #1363 are of potentially compound / undefined cause it might be best to close these issues as redundant due to re-install workaround. Not ideal I know but it's best we have issues as focused as possible which I know you were working towards but they can always be re-opened if reproducible steps can be found so that the root cause might be addressed in the code.

Thanks and I hope this install works out better than the last. Things are generally improving, release by release. Also might be as well to take a config backup and download the resulting file (via the Web-UI) once you have things configured up again.

**Closed** 2023-12-19 19:52 UTC
