### ISSUE TITLE
SAMA Service stays Off after reboot

### ISSUE THREAD

**Issue by valsimots** [rockstor/rockstor-core#2175] opened 2020-05-29 13:12 UTC
Rockstor 3.9.2-57
Linux: 4.12.4-1.el7.elrepo.x86_64

Upon reboot, SAMBA service does not automatically start.

**Comment by FroggyFlox** [comment] 2020-05-30 01:08
Hi @valsimots , thanks for bringing light on that... I immediately think of a recent issue we seem to experience with a newer Samba update on our CentOS base so I'm wondering whether Samba is correctly enabled but fails to start.

I would guide you towards the recent thread of interest on our forum:
[https://forum.rockstor.com/t/samba-fails-to-start-on-fresh-install-3-9-1-16/7109/6](https://forum.rockstor.com/t/samba-fails-to-start-on-fresh-install-3-9-1-16/7109/6?u=flox)

If this doesn't help, don't hesitate to open a new thread on our forum with as much details as you can think of so that we can reproduce the problem.
For Samba, I would include:
```
yum info samba samba-winbind libwbclient
```
as well as:
```
cat /etc/systemd/system/smb.service
```
and the output of the commands below after trying to toggle the Samba service from the webUI:
```
systemctl status smb nmb
```

Hope this helps, and I'm looking forward to seeing you on the forum (whether you still need troubleshooting or not).

Cheers,

**Comment by FroggyFlox** [comment] 2023-03-11 16:43
I'm closing this now as there seems to be no sign of a persisting issue.
@valsimots, feel free to post on our forum (https://forum.rockstor.com) if you are still having a problem.

**Closed by FroggyFlox** 2023-03-11 16:43 UTC
