### ISSUE TITLE
Minor issue on web ui - "Total capacity, allocation and usage" widget not resizing

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1225] opened 2016-03-22 13:17 UTC
As for my title, here are 2 screenshots:

**Widget enlarged don't fit container size**
![widget enlarged](https://cloud.githubusercontent.com/assets/17988902/13952749/802d5d30-f038-11e5-8825-68a4dbd43232.jpg)

Dashboard reloaded widget ok on large format
Widget reduced overfit div
![over](https://cloud.githubusercontent.com/assets/17988902/13952796/c161fbee-f038-11e5-9e6d-e01f3fe71a60.jpg)

All others seem ok
This is a really really minor issue, i know it

**Comment by phillxnet** [comment] 2016-03-22 15:33
@MFlyer Thanks for reporting, minor or not. Nice find.
Just reproduced here on Chrome Version 49.0.2623.87 and Firefox 45.0 in Fedora 23.

Total Capacity widget in top left, expand (widget contents doesn't rescale), refresh browser and widget contents refreshes to large then reduce widget again and as you found widget contents are not rescaling to the new smaller widget size either.

So looks like this particular widget's contents are not auto resizing like the others do.
Good to know.

**Comment by MFlyer** [comment] 2016-04-09 09:44
More info about this bug, found where it fails:

Uncaught TypeError: this.setGraphDimensions is not a function

**Comment by schakrava** [comment] 2016-05-11 04:26
Fixed by #1293

**Closed by schakrava** 2016-05-11 04:26 UTC
Labels: bug
