### ISSUE TITLE
SMART access failing for USB Flash Drive

### ISSUE THREAD

**Issue by ajkajk** [rockstor/rockstor-core#1684] opened 2017-03-28 16:53 UTC
Whilst trying to track down a problem with scrubbing, I looked at the Rockstor log.  This was pretty much unreadable as it consisted almost entirely of failures to read SMART status - these occur every minute.  It looks like the code in smart.py (available li 306 and/or get_device_options li 388) is not working for this device.  
If I call smartctl directly it reports SMART support available and enabled.
 ```smartctl --info /dev/sde3
smartctl 6.2 2013-07-26 r3841 [x86_64-linux-4.8.7-1.el7.elrepo.x86_64] (local build)
Copyright (C) 2002-13, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               SanDisk
Product:              Extreme
Revision:             0001
User Capacity:        16,013,942,784 bytes [16.0 GB]
Logical block size:   512 bytes
Logical Unit id:      0x6001b4402e460aaf0000000000000000
Serial number:        0462eaf0a
Device type:          disk
Local Time is:        Tue Mar 28 16:30:27 2017 BST
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Disabled or Not Supported
```
If I call using the id that rockstor generates I get
```smartctl --info /dev/disk/by-id/usb-SanDisk_Extreme_AA010404150345052563-0:0
smartctl 6.2 2013-07-26 r3841 [x86_64-linux-4.8.7-1.el7.elrepo.x86_64] (local build)
Copyright (C) 2002-13, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/disk/by-id/usb-SanDisk_Extreme_AA010404150345052563-0:0: Unknown USB bridge [0x0781:0x5580 (0x010)]
Please specify device type with the -d option.
```
Am I supposed to work out an option to add to the configuration?  If so how do I go about that? In any case I think such devices should be supported out of the box.  Would a call of ```os.path.realpath``` to convert to the ```/dev/sdX``` device name be a way forward?  (Perhaps filling up the log in this way without alerting the user that something is going wrong on the UI could be handled better - at least some count of errors logged displayed on the dashboard.)

**Comment by phillxnet** [comment] 2017-03-29 13:30
@ajkajk Thanks for your report, I particular like the log count idea and this should come in time as we have open issues concerning logging that should address this. The behaviour 'as is' comes from our silently assessing a drives smart capability by simply trying to get info from it and then if there is an error logging it and considering the device non smart compliant.  The issue re SanDisk Extreme and many devices is that often a base device call will yield different information to a partition on that device. We call on the base device as that seems to provide more useful info across devices.

One complication of smart capability and assessment is that we also cater for smart through raid controllers (partially) and that added quite  a degree of complexity but I think for a good outcome. Anyway the issue is a little more complicated than it first appears. 

The structure of drive management within Rockstor means we often end up with a partition if the device is on the system disk. I have several of these devices myself as I rather like that they are essentially an ssd on a stick with an usb-sata controller.

Anyway one complication is that I am not able to reproduce your findings as you didn't include the commands you used however I think I can make a good guess at them. Here is one of my SanDisk Extreme USB 3.0 drives:
```
 ls -la /dev/disk/by-id/ | grep usb-SanDisk
lrwxrwxrwx 1 root root   9 Mar 29 13:47 usb-SanDisk_Extreme_AA011217150507460372-0:0 -> ../../sda
lrwxrwxrwx 1 root root  10 Mar 29 13:47 usb-SanDisk_Extreme_AA011217150507460372-0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root  10 Mar 29 13:47 usb-SanDisk_Extreme_AA011217150507460372-0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  10 Mar 29 13:47 usb-SanDisk_Extreme_AA011217150507460372-0:0-part3 -> ../../sda3

```
So a call to the base device by-id results in:
```
smartctl -a /dev/disk/by-id/usb-SanDisk_Extreme_AA011217150507460372-0\:0
smartctl 6.2 2013-07-26 r3841 [x86_64-linux-4.8.7-1.el7.elrepo.x86_64] (local build)
Copyright (C) 2002-13, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/disk/by-id/usb-SanDisk_Extreme_AA011217150507460372-0:0: Unknown USB bridge [0x0781:0x5580 (0x010)]
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
```
it's canonical though temp name of "sda" call is identical (given it's a symbolic link)
```
smartctl -a /dev/sda
smartctl 6.2 2013-07-26 r3841 [x86_64-linux-4.8.7-1.el7.elrepo.x86_64] (local build)
Copyright (C) 2002-13, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sda: Unknown USB bridge [0x0781:0x5580 (0x010)]
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
```
What I suspect you have encountered is the difference between a call to a partition and a call to the base device, ie the following is a call to the first partition on the same device:
```
smartctl -a /dev/sda1
smartctl 6.2 2013-07-26 r3841 [x86_64-linux-4.8.7-1.el7.elrepo.x86_64] (local build)
Copyright (C) 2002-13, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               SanDisk
Product:              Extreme
Revision:             0001
User Capacity:        31,376,707,072 bytes [31.3 GB]
Logical block size:   512 bytes
Logical Unit id:      0x6001b4404264bb950000000000000000
Serial number:        0644295bb
Device type:          disk
Local Time is:        Wed Mar 29 13:54:41 2017 BST
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Disabled or Not Supported

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

Error Counter logging not supported

Device does not support Self Test logging
```
A very minimal report I think you will agree.

However if you observe the additional information that is available from the same device, but when calling it's base name (caveat of custom options required):
```
smartctl -d sat -a /dev/sda
smartctl 6.2 2013-07-26 r3841 [x86_64-linux-4.8.7-1.el7.elrepo.x86_64] (local build)
Copyright (C) 2002-13, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     SanDisk pSSD
Serial Number:    0644295bb
LU WWN Device Id: 5 001b44 04264bb95
Firmware Version: 3
User Capacity:    31,376,707,072 bytes [31.3 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ATA8-ACS T13/1699-D revision 2d
SATA Version is:  SATA 2.6, 6.0 Gb/s (current: 3.0 Gb/s)
Local Time is:    Wed Mar 29 13:56:53 2017 BST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART STATUS RETURN: incomplete response, ATA output registers missing
SMART overall-health self-assessment test result: PASSED
Warning: This result is based on an Attribute check.

General SMART Values:
Offline data collection status:  (0x00)	Offline data collection activity
					was never started.
					Auto Offline Data Collection: Disabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever 
					been run.
Total time to complete Offline 
data collection: 		(  120) seconds.
Offline data collection
capabilities: 			 (0x51) SMART execute Offline immediate.
					No Auto Offline data collection support.
					Suspend Offline collection upon new
					command.
					No Offline surface scan supported.
					Self-test supported.
					No Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   2) minutes.
Extended self-test routine
recommended polling time: 	 (   7) minutes.

SMART Attributes Data Structure revision number: 1
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  5 Reallocated_Sector_Ct   0x0002   100   100   000    Old_age   Always       -       0
  9 Power_On_Hours          0x0002   100   100   000    Old_age   Always       -       424
 12 Power_Cycle_Count       0x0002   100   100   000    Old_age   Always       -       232
171 Unknown_Attribute       0x0002   100   100   000    Old_age   Always       -       0
172 Unknown_Attribute       0x0002   100   100   000    Old_age   Always       -       0
173 Unknown_Attribute       0x0002   100   100   000    Old_age   Always       -       1
174 Unknown_Attribute       0x0002   100   100   000    Old_age   Always       -       69
187 Reported_Uncorrect      0x0002   100   100   000    Old_age   Always       -       0
230 Unknown_SSD_Attribute   0x0002   100   100   000    Old_age   Always       -       3
232 Available_Reservd_Space 0x0003   100   100   005    Pre-fail  Always       -       0
234 Unknown_Attribute       0x0002   100   100   000    Old_age   Always       -       7
241 Total_LBAs_Written      0x0002   100   100   000    Old_age   Always       -       81828546
242 Total_LBAs_Read         0x0002   100   100   000    Old_age   Always       -       42038128

SMART Error Log Version: 1
No Errors Logged

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Extended offline    Completed without error       10%        61         -
# 2  Short offline       Completed without error       00%        45         -

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.
```
I hope that you agree the inconvenience of the additional (as yet non auto detected by smart):
```
-d sat
```
custom option is worth it.

This was actually quite a hard won find after testing quite a few devices as I had always assumed there would be no difference.

Could you try adding the additional "-d sat" and see how you go. Your smart info and test capabilities gained may well be worth it.  The key here is "Not in smartctl database [for details use: -P showall]" so in time this additional base call may well be recognised as the smartmontools db develops to auto identify this devices type when called by it's base name. Hence the error of "Please specify device type with the -d option."

Please also see our recently added: S.M.A.R.T doc section:
http://rockstor.com/docs/smart/smart.html#s-m-a-r-t
and specifically the "Add Drive Specific Custom S.M.A.R.T Options" sub section:
http://rockstor.com/docs/smart/smart.html#add-drive-specific-custom-s-m-a-r-t-options

I propose that this issue be closed as it primarily relates to log filtering / monitoring which the upstream auto identification of base device calls to a SanDisk Extreme USB 3.0 device highlighted.

We have open log related issues of #606 and #701, in mentioning them here those issues will now have a reference back to this example of where better log management / event notification would have helped.

I hope you agree with this assessment and maybe if you have the time a report to the smartmontools project on auto identifying this device would be the way to go. That way we inherit that db once it trickles down to us and our CentOS 7 base.  I have reported devices not in the db myself but haven't followed the mailing list for quite some time now.

Hope that helps.

In the future do please consider using our forum as there are greater facilities and more users to help and benefit from such interchanges. There after a GitHub issue can be created drawing on any discussion that might have helped to narrow down the problem first.

https://forum.rockstor.com/

Thanks again for reporting your findings.

**Comment by ajkajk** [comment] 2017-04-02 15:20
@phillxnet 

Phil

Thanks for your comprehensive and thoughtful reply.

i) Apologies for not using the forum.  I tried, but the system didn't log me in with github credentials as I understand it was supposed to support, and in the end I ended up in github in the issues section and just posted there.  I'll try to do better in future.

ii) I didn't save the console log for the putty session that I used when investigating the smartctl operation.  I can no longer reproduce the command I used to generate SMART information from the Sandisk Extreme by quoting the /dev/sde address, rather than the /by-id one.  I guess that's no surprise to you, but is to me - I've no idea what I did unless I got some Windows console output mixed up with Linux output.  Apologies again!

iii) I can confirm that explicitly telling smartctl how to access the usb connected device using the -d sat option is working for me  The Rockstor log is no longer filling up with messages reporting the same failure repeatedly.  Thanks.  

iv) I have read the documentation you pointed me - thank you for your forbearance.  It would be good if those links were in some way included in the GUI on the SMART/discs page and/or the message in the rockstor log.  It's slightly odd (to me) for this particular problem to be reported as a repeated failure of a procedure call in the Rockstor log.

v) Given that as I understand it the whole point of the code polling the discs attached is to match up the current discs to the ones Rockstor has seen in the past, it seems odd not to remember that the smartctl command will fail for this disc instead of trying it again - if you do what you've always done, you'll get what you always get.  Even if you want to try again, there is absolutely no point in logging the same fail again and filing up the log (except if the scan is in response to a rescan request to make your documentation suggesting the logs is examined remain true!)

vi) The Sandisk Extreme is supported in the latest version (May 2016 6.5) at least on Windows i.e. all the attributes are reported as expected - no problems dealing with the USB bridge in the device.  Rockstor reports it is shipping with version 6.2 (July 2013 - although compiled Nov 2016).  That's four years old.  I don't think there is much point in my reporting back to them at this time.  If I'm right, then it might be better for Rockstor to ship with the latest version.

Thanks again for you support (and forbearance)

Andy

**Comment by phillxnet** [comment] 2017-04-02 16:15
@ajkajk Totally agree.

As per your suggestion re re-scanning devices and seeing if they support smart a few seconds after they last reported not doing so is a little 'over the top' but this is primarily down to our current polling model and we hope in the future to more to an event driven scan, ie if udev notices something drive related has changed then we go through the rather long winded re-scanning process. This would then alleviate the issue and the rescan of what was found before would stand in better stead to cope with such things as smartmontools db updates where the support for a device may have been added since the last disk change was detected.

As for the "It's slightly odd (to me) for this particular problem to be reported as a repeated failure of a procedure call in the Rockstor log." Yes there is inelegance there but smart support status is a tricky one to establish, you pretty much have to try it and see. Again the repeat will be removed once we move to an event model of update.

We are getting there bit by bit though.

As per old versions of software (smartmontools) we pretty strictly adhere to whatever CentOS is dishing out as that is our base. Only in a very few instances do our package versions differ. That way we inherit their stability in those packages (hopefully).

Glad you are now sorted with the -d sat option and good idea re-adding contextual links within the UI. As it goes that doc is pretty new and I am actually adding disk role related links to it from the UI in my current LUKS related issue so hopefully the same can be done for the smart related config page which was added quite a long time before the docs for it existed. Slight chicken and egg on these things often.

Definitely give the forum sign up another go, I signed in with my GitHub ID but that was quite a while ago now. If you have issues again try opening an issue here for the problem you experience.

Hope that helps.

Please feel free to close this issue as the observed failure is considered an upstream package version issue and we are unlikely to do a better job of maintaining smartmontools than the CentOS folks, at least until we get one of the smartmontools team on board that is. Or as a log monitoring related issue as discussed earlier of course.

My understanding is that one can update the smartmontools db 'in place' via a command contained within the existing package: maybe you fancy opening an issue for us to incorporate that feature within the UI (details of how it is done via the command line would also help of course). That may very well address the problem you reported from another angle.

**Closed** 2017-04-03 12:44 UTC

**Comment by ajkajk** [comment] 2017-04-03 12:47
Closed as a work-round is available to avoid filling the log up, and eventually the device will be directly supported when the latest version of the smartctl package is included in Centos upstream.
