### ISSUE TITLE
Rockstor js libs out of date

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1455] opened 2016-09-30 01:48 UTC
Hi all,
while on latest PR coding found our current Backbone lib is 0.9.2 against current 1.3.3 and same for other libs.
What do you think about updating our jslibs? (ex.: latest backbone has new useful features like optional parameters on router.js, etc etc)

@priyaganti ?

**Comment by sfranzen** [comment] 2016-09-30 10:49
:+1: I upgraded backbone temporarily on my VM to see if it would fix an issue. In the end I fixed the issue in another way, but I found an API incompatibility with 0.9.2 that will need attention. Namely: the `options` parameters you can pass into constructors is no longer implicitly assigned to `this.options`. I didn't check how often we use `this.options`, but there are [several ways](http://stackoverflow.com/questions/19325323/backbone-1-1-0-views-reading-options) of fixing.

**Comment by schakrava** [comment] 2017-03-24 21:23
updating backbone is a great idea, but it also involves thorough testing to prevent regressions. @sfranzen's pr is a great start, but we need more work to push it to completion.

**Comment by FroggyFlox** [comment] 2023-12-19 16:54
Closing this issue as a tad too broad, unfortunately, but mostly due to our recent effort in reducing our JS dependencies (#2735).

**Closed by FroggyFlox** 2023-12-19 16:54 UTC
Labels: enhancement
