### ISSUE TITLE
Cannot start rock-ons service:  Unknown internal error doing a POST to /api/sm/services/docker/start 

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#966] opened 2015-10-19 05:28 UTC
Traceback (most recent call last):
      File "/opt/rockstor/eggs/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
        result = self._run(*self.args, **self.kwargs)
      File "/opt/rockstor/src/rockstor/smart_manager/data_collector.py", line 263, in send_service_statuses
        output, error, return_code = service_status(service)
      File "/opt/rockstor/src/rockstor/system/services.py", line 163, in service_status
        return init_service_op(service_name, 'status', throw=False)
      File "/opt/rockstor/src/rockstor/system/services.py", line 52, in init_service_op
        raise Exception('unknown service: %s' % service_name)
    Exception: unknown service: service-monitor
    <Greenlet at 0x33f3050: <bound method ServicesNamespace.send_service_statuses of     <smart_manager.data_collector.ServicesNamespace object at 0x33eeb50>>> failed with Exception

**Comment by roweryan** [comment] 2015-10-19 05:29
3.8-8.11

**Comment by roweryan** [comment] 2015-11-05 21:47
3.8-9.01 and it's working better, but I still get the error the first time I load the rock-ons page that the service is not running, even when it is. Refresh clears that.

**Comment by roweryan** [comment] 2015-11-05 21:58
Reboot into newer kernel seems to fix it.

**Comment by schakrava** [comment] 2015-11-20 20:34
Thanks for reporting this @roweryan . I am glad it's working for you now, but I doubt it has anything to do with kernel update. Let me know if you are able to reproduce it again.

**Comment by schakrava** [comment] 2015-12-28 01:04
I am unable to reproduce this issue, so closing for now. Please do reopen with reproducible steps if you run into it again.

**Closed by schakrava** 2015-12-28 01:04 UTC
Labels: bug
