### ISSUE TITLE
Dashboard widget resizing is glitchy in Chrome on Mac

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1530] opened 2016-11-16 12:57 UTC
A user reported that resizing disk activity widget on dashboard causes the boundaries to overlap. This was reported on Mac 10.11.6 with latest Chrome and Firefox. Apparently the behavior is the same on WIndows 10 with Chrome.

I've confirmed it on Mac with Chrome version 53.0.2785.113. I cannot reproduce it on Linux+Chrome or Firefox.

Finally, to reproduce on Mac+Chrome all you need to do is go to the dashboard and expand Disk activity widget and perhaps another one(eg: Network) if you don't see the issue already. Below screen shot shows the issue.

<img width="1084" alt="dashboard_glitch" src="https://cloud.githubusercontent.com/assets/1123552/20348197/27031f0a-abb9-11e6-850e-39866337dcd8.png">

**Comment by MFlyer** [comment] 2016-11-16 13:37
Hi @schakrava ,
got some initial tests and these don't help us (not able to reproduce):

WIN 7 + Chrome 54.0.2840.99 (latest)-> No overlapping, all fine
WIN 7 + Firefox 50 (latest)-> No overlapping, all fine

Had some time playing removing/adding widgets, having all maximized, some maximized, some not, but it was all ok.
Any idea if user having some add-on on firefox/chrome??

**Comment by MFlyer** [comment] 2016-11-16 17:00
Had another relaxing 20mins playing with widgets, but without success.
Tomorrow going to check over a WIN10 system
M.

**Comment by MFlyer** [comment] 2016-11-16 17:28
Hi @schakrava , while checking templates found this -> 003fb9a

Can you test it if solves over a Mac? a wrapper div always required by canvas (no wrapper => canvas overlapping on resize), but having 2 divs with same ID probably made it crazy

Waiting your checks :)

**Comment by MFlyer** [comment] 2016-12-17 09:10
> Apparently the behavior is the same on WIndows 10 with Chrome

Good UTC morning @schakrava :) , with my new laptop going to test this on WIN10 too so hopefully will have better chance to catch it.

**Comment by MFlyer** [comment] 2017-01-02 20:11
Hi @schakrava,
after Xmas flu and a battle vs win10 & wifi finally got my new laptop running with dual boot and...reproduced this issue :)

Hope to solve asap, there's an error raising when resizing from small to big

M.

**Comment by MFlyer** [comment] 2017-01-03 19:40
Got an update about this, @schakrava & @phillxnet can you check too?
Accidentally played with WIN10 resolution and FONT SCALING, WIN10 on a wide screen has 125% default...moving it to 100% (normal) Disk Widget feels ok.

Looking anyway for a solution :wink

**Comment by phillxnet** [comment] 2017-01-03 20:06
@MFlyer Sorry I am, fortunately for me at least, without a Win10 machine (a state I intend to maintain by the way). And my OSX machine is still out on loan (apparently it's a long loan :) ) Didn't the original issue also show up in Firefox, at least with OSX?

**Comment by MFlyer** [comment] 2017-01-03 21:17
>  without a Win10 machine (a state I intend to maintain by the way)
😭 
New laptop -> 7th Gen Intel -> supported only Linux and Win10 (obviously got a dual boot) -> no way with previous win sys :/

**Comment by MFlyer** [comment] 2017-01-04 08:39
Tested on a second win10 machine and can confirm - on windows side - related to screen scaling (125% -> bad dashboard widget, 100% -> ok)

M.

**Closed** 2017-01-05 13:09 UTC
Labels: bug
