### ISSUE TITLE
Problems with scheduled snapshots and snapshot cleanup

### ISSUE THREAD

**Issue by belaz9** [rockstor/rockstor-core#1788] opened 2017-08-07 01:29 UTC
My system is having problems with deleting old snapshots and creating new ones:
Rockstor 3.9.1-0
Seems related to 3.9.1 update, was working fine before the update.

[04/Aug/2017 23:42:02] ERROR [scripts.scheduled_tasks.snapshot:70] Failed to delete old snapshots exceeding the maximum count(30)
[04/Aug/2017 23:42:02] ERROR [scripts.scheduled_tasks.snapshot:71] Exception while setting access_token for url(http://127.0.0.1:8000): No JSON object could be decoded. content: None
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/scripts/scheduled_tasks/snapshot.py", line 67, in delete
    aw.api_call(url, data=None, calltype='delete', save_error=False)
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 75, in api_call
    self.set_token()
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 69, in set_token
    raise Exception(msg)
Exception: Exception while setting access_token for url(http://127.0.0.1:8000): No JSON object could be decoded. content: None

Cron <root@rs> /opt/rockstor/bin/st-snapshot 1
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python2.7/logging/handlers.py", line 154, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 324, in getMessage
    msg = str(self.msg)
TypeError: __str__ returned non-string (type list)
Logged from file snapshot.py, line 71

**Comment by phillxnet** [comment] 2017-08-22 15:10
@belaz9 Thanks for reporting this issue and apologies for the slow response. I have a suspicion on what may have happened here and it relates to a potential regression of a pool API change we had to make but that caused a few issue that we are now addressing. I am currently working in another area of the code (but a related one) however it would be helpful in the mean time if you could try deleting your existing snap shot scheduled task and re-creating it 'a-fresh'. It may be that this sorts your issue but if not it will help to identify the problem.

Thanks for the detailed issue reported.

**Comment by phillxnet** [comment] 2017-08-23 12:06
@belaz9 had a quick look at this and pretty sure my original suspicion re recent API changes does not affect scheduled snapshot management as only disk and pool API's were changed. Snapshots seem to work purely on a name basis still. Did deleting the snapshot task and re-creating it work?

I have not managed to re-produce you issue as of yet and snapshot function 'from a fresh task' appears to work as intended.

The following:
ERROR [scripts.scheduled_tasks.snapshot:71] Exception while setting access_token for url(http://127.0.0.1:8000): No JSON object could be decoded. content: None
suggests there is some access issue to the https API in order to perform the snapshot removal.

@MFlyer and @priyaganti and @schakrava this looks to be more in your areas; any idea what could lead to this 'setting access_token' issue? Don't see any other reports of this (issues or forum threads).

**Comment by belaz9** [comment] 2017-08-23 15:16
Yes, after deleting and recreating snapshots they are working correctly now, so this was an upgrade issue.
Thanks.

**Comment by phillxnet** [comment] 2017-08-23 15:33
@belaz9 Thanks for the feedback and confirmation of work around. Do you fancy closing the issue as without a method to reproduce it's a tricky one to address. And we now at least have a record (your report in this issue) of a successful work around.

Cheers.

**Closed** 2017-08-23 16:04 UTC
