### ISSUE TITLE
Menu button in mobile site doesn't work

### ISSUE THREAD

**Issue by modelrockettier** [rockstor/rockstor-core#810] opened 2015-08-22 05:15 UTC
Tested with Firefox and Chrome on windows (make the browser window small), and with Dolphin and Chrome on android.

In all cases, the button in the top-right of the screen which I assume to be a menu button does not react when you click or tap it.

Rockstor 3.8-5.

**Comment by phillxnet** [comment] 2015-08-30 17:38
@modelrockettier I believe this has now been fixed by @snamstorm in issue #832 and should appear in the next release.
@schakrava marking as duplicate of now closed #832 .

**Comment by schakrava** [comment] 2015-10-05 01:12
Thanks @phillxnet . I am closing this issue.

**Closed by schakrava** 2015-10-05 01:12 UTC
