### ISSUE TITLE
task scheduler not working

### ISSUE THREAD

**Issue by xavierle** [rockstor/rockstor-core#743] opened 2015-07-15 19:27 UTC
i have this error when accessing to task scheduler

Unknown internal error doing a GET to /api/sm/tasks/log?page=1&format=json&page_size=5000&count=

**Comment by phillxnet** [comment] 2015-07-16 09:24
@xavierle Thanks for opening this issue. We have an existing issue open #728 however the error there looks different from yours and is reproducibly by attempting to edit an existing task.

What are the steps needed to reproduce your error and does it still occur with the just released 3.8-3 update? Thanks for your assistance.

**Comment by Mchakravartula** [comment] 2015-07-16 12:41
I can confirm this still exists in 3.8-3. Clicking the edit button after created a scheduled scrub displays error as mentioned in #728. After you get this error when you try to refresh scheduled-tasks page or click on  'Scheduled Tasks' the the error mention by @xavierle  is displayed.

**Comment by phillxnet** [comment] 2015-07-16 13:34
@Mchakravartula that's a nice find; however I can't reproduce that finding here, either in Chrome or Firefox; I don't know why though.  I have followed your exacting directions but alas I only get the same #728 error not this one.  I have one scheduled scrub task previously made and have rebooted a few times since that task was made, note however that the task has never been run. This is with 3.8-3 which use to be 3.8-2. However I have only tried to reproduce you finding on a single VM as have to dash.

**Comment by xavierle** [comment] 2015-07-16 17:20
if i cannot schedule snapshot, rockstor and btrfs are not useful

i keep my test rockstor machine on hold until this issue is solved.
it makes 2 3 times i test rockstor but always suffering issues

in the meantime, i keep with omv

**Comment by schakrava** [comment] 2015-07-17 04:51
Totally agree with you, scheduling snapshots is a pretty fundamental feature that should not be broken. I've increased the priority on this issue. We'll get to it soon and update you. Thanks for your patience.

**Comment by schakrava** [comment] 2015-07-23 19:31
@xavierle thanks for reporting this issue. We have fixed it pending more testing and merge and as @phillxnet guessed, the root cause is same as #728 . So, I am closing this as a duplicate.

**Closed** 2015-07-23 19:31 UTC
Labels: bug, Critical, duplicate

**Comment by skubic** [comment] 2015-10-31 20:28
same here. fresh installation in virtual box. btrfs layout, of course. installs just fine. after reboot entered the ui for giving in user details. after pressing the next button:

Error!
Unknown internal error doing a GET to /api/appliances?page=1&format=json&page_size=5000&count=
If you need more help on this issue, email us at support@rockstor.com with the following information:

    The error message: "Unknown internal error doing a GET to /api/appliances?page=1&format=json&page_size=5000&count="
    A step by step description of the actions leading up to the error.
    Download the tarred and zipped server logs by clicking here, and attach it to the email.
