### ISSUE TITLE
AD enable in 4.0.5-0 (RC6) requires reboot or rockstor service restart

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2240] opened 2021-01-03 15:15 UTC
Thanks to @FroggyFlox for helping to diagnose this issue. As of 4.0.5-0 (Release Candidate 6) enabling the newly added sssd backed AD service for the first time leads to the following error:

KeyError: u"Got KeyError when attempting to get a value for field `groupname` on serializer `SUserSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `User` instance.\nOriginal exception text was: 'getgrgid(): gid not found: ...

Where the gid is that of the AD users.

Linking to the relevant pull request where this issue was discovered:
"Implement SSSD-based enrollment into Active Directory or LDAP domains." #2235

A subsequent reboot or rockstor service restart resolves the apparent caching issue and functionality looks to be as expected there after.

**Comment by FroggyFlox** [comment] 2021-01-13 21:18
Linking to previous conversation as it contains some potentially helpful pointers for resolution of this issue:
https://github.com/rockstor/rockstor-core/pull/2235#issuecomment-753482286

**Comment by FroggyFlox** [comment] 2021-01-21 19:49
Another link to a previous issue in this very repo tracking this down to winbind: https://github.com/rockstor/rockstor-core/issues/1817#issuecomment-334804104

May not be related to winbind anymore in our case as we're now on a much newer base, but could be worth investigating nonetheless.

**Comment by FroggyFlox** [comment] 2021-02-06 14:51
After some investigation, it seems that the workaround listed in https://github.com/SSSD/sssd/issues/4858 is indeed working in our case as well... Unfortunately, I'm not sure whether it can be implemented or not as it does require to know the domain group name beforehand but I'll dig deeper.
As a reminder, the workaround listed there is to call `grp.getgrnam(<groupname@domain>)` first before trying to fetch it via `grp.getgrgid(gid)`.

**Comment by FroggyFlox** [comment] 2021-02-08 01:16
After quite a few attempts at understanding exactly why we cannot fetch the domain users freshly "joined" with the python `grp` module, I'm starting to believe online reports stating that `grp` simply cannot fetch remote users and that alternatives such as `getent passwd/groups` should be used. The thing that puzzles me is that we can indeed fetch these users with `grp` upon restarting gunicorn/rockstor.

Regardless, I believe we should implement some sort of failover mechanism when we can't fetch users like we're experiencing here, which we would also help harmonize how we fetch users and groups information. Indeed, we currently use:
- `getent passwd` to fetch _user_ info
- the python `grp` module to fetch _groups_ information

This actually explains why we are seeing this very issue: we try to fetch the group information using `grp` for a user detected using `getent passwd`. As the former cannot see remote users but the latter can, we end up with the `gid not found` error.

Because I don't think we should refactor entirely how we fetch the *groups* information, I'm thinking of writing a failover mechanism that would try to fetch the needed info if the `grp` fails. In this case, we would:
1. be able to fetch all users/groups information right after joining an AD/LDAP domain
2. still rely on current mechanisms to fetch all this information after `gunicorn`/`rockstor` service restart.

In an effort to homogenize our `groups` fetching logic with our `users` fetching one, the first mechanism that comes to mind is to use `getent groups`. There might be an interesting alternative, though: the D-Bus interface written especially for that by the SSSD folks (it does offer several bindings, including for python). I'm not sure we would see much difference from a performance perspective, but the D-Bus API of SSSD seems to be designed to access more than POSIX user/groups attributes; although we do not take advantage of these at the moment, it might be interesting in the future. In this context, it could be valuable to lay the groundwork to use this API so that we have the possibility to expand our options in the future...
Some interesting description + illustration and example of its python binding can be found in the following slides by the SSSD team: https://jhrozek.fedorapeople.org/SSSD%20DBUS%20API%20tech%20talk.pdf

**Comment by phillxnet** [comment] 2021-02-08 11:02
@FroggyFlox Re:
> In this context, it could be valuable to lay the groundwork to use this API so that we have the possibility to expand our options in the future...
Definitely, and this is in keeping with our next major task of updating all our dependencies so we can more easily integrate newer ways of doing things. And given your recent push on the SSSD front it makes sense to use this where ever we can. And the extended user attributes abilities has to be a plus in this case. Also:
"D-Bus signal support is being added"
sound promising. I'd really like to be moving away from a polling model.
All in good time.

Thanks for the detailed reports / updates. Always better if we can rely on specialist subsystems if we can.

**Comment by FroggyFlox** [comment] 2021-02-08 17:39
The SSSD D-Bus API is called **InfoPipe** and is documented here:
https://sssd.io/docs/design_pages/dbus_users_and_groups.html

It would require the following packages:
- `python-dbus-python`
- `sssd-dbus`

It would require the activation of the `infopipe` service in `sssd.conf`:
```
[sssd]
(...)
services = nss, pam, ifp
```

Initializing the DBus interface and fetch the groups for the `Administrator@samdom.example.com` would be:
```python
def get_ifp_groups():
    bus = dbus.SystemBus()
    users_obj = bus.get_object(
        "org.freedesktop.sssd.infopipe", "/org/freedesktop/sssd/infopipe/Users"
    )
    users_iface = dbus.Interface(users_obj, "org.freedesktop.sssd.infopipe.Users")
    # users_iface.FindByName("Administrator@samdom.example.com")
    # dbus.ObjectPath('/org/freedesktop/sssd/infopipe/Users/samdom_2eexample_2ecom/1367400500')

    admin_path = users_iface.FindByName("Administrator@samdom.example.com")
    admin_obj = bus.get_object("org.freedesktop.sssd.infopipe", admin_path)
    admin_iface = dbus.Interface(admin_obj, "org.freedesktop.DBus.Properties")
    # admin_iface.Get("org.freedesktop.sssd.infopipe.Users.User", "groups")
    admin_groups = admin_iface.Get("org.freedesktop.sssd.infopipe.Users.User", "groups")
    return admin_groups
```

Groups can be fetched using a similar approach.
Based on the documentation:
- the `User` interface has the following properties:
https://sssd.io/docs/design_pages/dbus_users_and_groups.html#orgfreedesktopsssdinfopipeusersuser
- the `Group` interface has the following properties:
https://sssd.io/docs/design_pages/dbus_users_and_groups.html#orgfreedesktopsssdinfopipegroupsgroup

The current issue arises when trying to fetch the groupname for a given gid. We should thus be able to use the `User` interface to get the user's `gid`, and then use that to fetch the group using the `Groups` interface and its `FindByID(u:id)`. followed by the `Group` interface to get its `groupname` property.

As a very crude comparison between `infopipe` and `grp`, upon visiting the System > Groups page:
- `grp` does not see the AD groups:
```
[08/Feb/2021 12:29:48] DEBUG [system.users:104] grp.getgrall() is = [grp.struct_group(gr_name='root', gr_passwd='x', gr_gid=0, gr_mem=['nginx']), grp.struct_group(gr_name='shadow', gr_passwd='x', gr_gid=15, gr_mem=[]), grp.struct_group(gr_name='trusted', gr_passwd='x', gr_gid=42, gr_mem=[]), grp.struct_group(gr_name='users', gr_passwd='x', gr_gid=100, gr_mem=[]), grp.struct_group(gr_name='messagebus', gr_passwd='x', gr_gid=499, gr_mem=[]), grp.struct_group(gr_name='kmem', gr_passwd='x', gr_gid=498, gr_mem=[]), grp.struct_group(gr_name='lock', gr_passwd='x', gr_gid=497, gr_mem=[]), grp.struct_group(gr_name='tty', gr_passwd='x', gr_gid=5, gr_mem=[]), grp.struct_group(gr_name='utmp', gr_passwd='x', gr_gid=496, gr_mem=[]), grp.struct_group(gr_name='audio', gr_passwd='x', gr_gid=495, gr_mem=[]), grp.struct_group(gr_name='cdrom', gr_passwd='x', gr_gid=494, gr_mem=[]), grp.struct_group(gr_name='dialout', gr_passwd='x', gr_gid=493, gr_mem=[]), grp.struct_group(gr_name='disk', gr_passwd='x', gr_gid=492, gr_mem=[]), grp.struct_group(gr_name='input', gr_passwd='x', gr_gid=491, gr_mem=[]), grp.struct_group(gr_name='kvm', gr_passwd='x', gr_gid=490, gr_mem=[]), grp.struct_group(gr_name='lp', gr_passwd='x', gr_gid=489, gr_mem=[]), grp.struct_group(gr_name='tape', gr_passwd='x', gr_gid=488, gr_mem=[]), grp.struct_group(gr_name='video', gr_passwd='x', gr_gid=487, gr_mem=[]), grp.struct_group(gr_name='systemd-coredump', gr_passwd='x', gr_gid=485, gr_mem=[]), grp.struct_group(gr_name='systemd-journal', gr_passwd='x', gr_gid=486, gr_mem=[]), grp.struct_group(gr_name='systemd-network', gr_passwd='x', gr_gid=483, gr_mem=[]), grp.struct_group(gr_name='systemd-timesync', gr_passwd='x', gr_gid=484, gr_mem=[]), grp.struct_group(gr_name='wheel', gr_passwd='x', gr_gid=482, gr_mem=[]), grp.struct_group(gr_name='daemon', gr_passwd='x', gr_gid=2, gr_mem=['upsd']), grp.struct_group(gr_name='mail', gr_passwd='!', gr_gid=481, gr_mem=['postfix']), grp.struct_group(gr_name='nogroup', gr_passwd='x', gr_gid=65533, gr_mem=['nobody']), grp.struct_group(gr_name='nobody', gr_passwd='x', gr_gid=65534, gr_mem=[]), grp.struct_group(gr_name='upsd', gr_passwd='!', gr_gid=480, gr_mem=[]), grp.struct_group(gr_name='sshd', gr_passwd='x', gr_gid=479, gr_mem=[]), grp.struct_group(gr_name='chrony', gr_passwd='x', gr_gid=478, gr_mem=[]), grp.struct_group(gr_name='ntp', gr_passwd='x', gr_gid=477, gr_mem=[]), grp.struct_group(gr_name='shellinabox', gr_passwd='x', gr_gid=476, gr_mem=[]), grp.struct_group(gr_name='nginx', gr_passwd='x', gr_gid=475, gr_mem=[]), grp.struct_group(gr_name='polkitd', gr_passwd='x', gr_gid=474, gr_mem=[]), grp.struct_group(gr_name='postgres', gr_passwd='x', gr_gid=26, gr_mem=[]), grp.struct_group(gr_name='postfix', gr_passwd='x', gr_gid=51, gr_mem=[]), grp.struct_group(gr_name='maildrop', gr_passwd='x', gr_gid=59, gr_mem=['postfix']), grp.struct_group(gr_name='avahi', gr_passwd='x', gr_gid=473, gr_mem=[]), grp.struct_group(gr_name='at', gr_passwd='x', gr_gid=25, gr_mem=[]), grp.struct_group(gr_name='docker', gr_passwd='x', gr_gid=472, gr_mem=[]), grp.struct_group(gr_name='dockremap', gr_passwd='!', gr_gid=471, gr_mem=[]), grp.struct_group(gr_name='winbind', gr_passwd='x', gr_gid=470, gr_mem=[]), grp.struct_group(gr_name='ntadmin', gr_passwd='x', gr_gid=71, gr_mem=[])]
```


- `infopipe` does see the AD groups, as evidence by the following attempt at fetching the groups for the "Administrator@samdom.example.com" user:
```
[08/Feb/2021 12:29:48] DEBUG [system.users:105] get_ifp_groups() is = dbus.Array([dbus.ObjectPath('/org/freedesktop/sssd/infopipe/Groups/samdom_2eexample_2ecom/1367400513'), dbus.ObjectPath('/org/freedesktop/sssd/infopipe/Groups/samdom_2eexample_2ecom/1367400519'), dbus.ObjectPath('/org/freedesktop/sssd/infopipe/Groups/samdom_2eexample_2ecom/1367400512'), dbus.ObjectPath('/org/freedesktop/sssd/infopipe/Groups/samdom_2eexample_2ecom/1367400518'), dbus.ObjectPath('/org/freedesktop/sssd/infopipe/Groups/samdom_2eexample_2ecom/1367400513'), dbus.ObjectPath('/org/freedesktop/sssd/infopipe/Groups/samdom_2eexample_2ecom/1367400572'), dbus.ObjectPath('/org/freedesktop/sssd/infopipe/Groups/samdom_2eexample_2ecom/1367400520')], signature=dbus.Signature('o'), variant_level=1)
```

**Important**: this diffference between `infopipe` and `grp` is only true when working from within Rockstor, as even `grp.getgrall()` sees the AD groups from a python shell opened separately... we thus really are trying to circumvent a limitation of our "special" python env used by gunicorn (it might also explain why a gunicorn restart fixes this issue).

**Comment by FroggyFlox** [comment] 2021-02-09 21:08
Current working example for fetching the groupname for a user's primary gid (we already get gid so we only need the ifp part to fetch the name of the group with a given `gid`):

```python
def ifp_get_groupname(gid):
    bus = dbus.SystemBus()

    groups_obj = bus.get_object('org.freedesktop.sssd.infopipe', '/org/freedesktop/sssd/infopipe/Groups')
    groups_iface = dbus.Interface(groups_obj, 'org.freedesktop.sssd.infopipe.Groups')

    my_obj = bus.get_object('org.freedesktop.sssd.infopipe', groups_iface.FindByID(gid))
    my_iface = dbus.Interface(my_obj, 'org.freedesktop.sssd.Groups.Group')
    my_iface_properties = dbus.Interface(my_obj, 'org.freedesktop.DBus.Properties')

    gpname = my_iface_properties.Get('org.freedesktop.sssd.infopipe.Groups.Group', 'name')
    return str(gpname)
```
Testing with:
```python
gid = 1367400513
ifp_get_groupname(gid)
# 'domain users@samdom.example.com'
```


This was heavily inspired by a very well written issue on SSSD's Github repo: https://github.com/SSSD/sssd/issues/5112

**Comment by FroggyFlox** [comment] 2021-02-12 20:51
Similarly, a logic to return all remote groups as seen by `infopipe` would be:

```python
def ifp_get_groups():
    bus = dbus.SystemBus()

    groups_obj = bus.get_object(
        "org.freedesktop.sssd.infopipe", "/org/freedesktop/sssd/infopipe/Groups"
    )
    groups_iface = dbus.Interface(groups_obj, "org.freedesktop.sssd.infopipe.Groups")
    allgroups = groups_iface.ListByName("*", 0)

    ifp_groups = {}
    for group in allgroups:
        my_obj = bus.get_object("org.freedesktop.sssd.infopipe", group)
        my_obj_properties = dbus.Interface(my_obj, "org.freedesktop.DBus.Properties")
        gpname = my_obj_properties.Get(
            "org.freedesktop.sssd.infopipe.Groups.Group", "name"
        )
        gpid = my_obj_properties.Get(
            "org.freedesktop.sssd.infopipe.Groups.Group", "gidNumber"
        )
        ifp_groups[gpname] = gpid

    return ifp_groups
```

**Comment by FroggyFlox** [comment] 2021-02-13 16:26
Found another previous issue reporting this very problem: https://github.com/rockstor/rockstor-core/issues/1580
The current issue should thus be considered as a duplicate of #1580 and all should be closed by the related PR.

**Comment by FroggyFlox** [comment] 2021-02-14 14:56
I now have a seemingly working implementation able to fetch remote `groups` from AD/LDAP servers when `grp` cannot yet see them.
I am now cleaning up the branch to then prepare a corresponding pull-request.

**Closed** 2021-03-08 08:37 UTC
