### ISSUE TITLE
network widget scale seems wrong

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#589] opened 2015-02-08 18:13 UTC
The network widget seems to show wrong numbers.
Here is a screenshot of the network widget while performing a backup from two machines to rockstor:
https://www.dropbox.com/s/v67ijuqtg7hs9hf/Schermafdruk%202015-02-07%2016.09.03.jpg?dl=0

Perhaps I am looking at this graph wrong, but I am fairly certain my network does not support 67gigabyte/second transfers!

**Comment by iFloris** [comment] 2015-02-09 13:32
Thanks for opening an issue.
My machine is an intel SSR212MC2, with a S5000PSL server board using two Intel 82563EB onboard NICs.

**Comment by MFlyer** [comment] 2016-12-08 10:47
Hi @schakrava , can we close this?? Actually on my env charts seem ok

M.

**Comment by MFlyer** [comment] 2017-01-30 13:39
Already fixed over #1457 @schakrava , we can close it

Mirko

**Comment by MFlyer** [comment] 2017-05-27 07:18
@schakrava this can be closed
M.

**Comment by FroggyFlox** [comment] 2023-10-25 21:50
Closing this as seems to be confirmed fixed above.

**Closed by FroggyFlox** 2023-10-25 21:50 UTC
Labels: bug
