### ISSUE TITLE
SCRUB fails to end / fails to restart after shutdown

### ISSUE THREAD

**Issue by arbrick** [rockstor/rockstor-core#1640] opened 2017-02-03 02:45 UTC
My box experienced an unexpected shutdown during the execution of a scrub, and I am now unable to schedule further scrubs or cancel the currently "running" one through the webui.
The box is running 3.8.16-8, but I believe the problem originated when it was running an older version. The problem has persisted across restarts and upgrades.

Link to origional post on rockstor forums [here](https://forum.rockstor.com/t/scrub-fails-to-end-fails-to-restart-after-shutdown/2769)

```bash
Traceback (most recent call last):
File "/opt/rockstor/eggs/gunicorn-0.16.1-py2.7.egg/gunicorn/workers/sync.py", line 34, in run
client, addr = self.socket.accept()
File "/usr/lib64/python2.7/socket.py", line 202, in accept
sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable
```

**Comment by lancebooth222** [comment] 2017-02-24 22:21
I am experiencing the exact same issue. I experienced an unplanned shutdown during a scrub, and I get the exact same error message. It persists across reboots and shutdowns. 

I am running the latest stable version of RockStor - 3.8.16-1.

Any help would be greatly appreciated.

Thank you,

Lance

**Comment by lancebooth222** [comment] 2017-03-25 07:25
I suspect this is probably related, but I am not sure... 

I just upgraded to 3.9.0-0 and now I get an error when attempting to access the web UI... Additionally, I get a failure during the Rockstor Bootstrap process, and when I attempt to browse the pools, which are still shown in the web UI, there are no files.

I opened a ticket with the exact specifications, but I can re-post the information here if you like.

In the meantime, if you haven't upgraded to the latest stable version, and have this issue, I would recommend NOT upgrading at this time. If you have and it was successful, I would like to information on that, also.

Thank you,

Lance

**Comment by phillxnet** [comment] 2017-08-08 14:43
@arbrick and @lancebooth222 (initial comment here) 2 possible causes for this behaviour have now been addressed in the following issues opened to more exactly articulate the separate causes that existed:
"improve scrub status reporting resolution #1786"
which covers the most likely cause, and a rather unfortunate concurrent bug in a possible work around:
"regression in 'force' option - scrub and balance #1790"
the 2 associated pending pull requests are (respectively):
#1791 
and
#1792 

I am marking this issue as a duplicate of #1786 although I appreciate that it was opened first. However #1786 and #1790 contain explanations of the mechanisms that lead to this issue.

Thanks again for reporting this.

**Closed** 2017-08-08 23:22 UTC
