### ISSUE TITLE
cannot acces pool information

### ISSUE THREAD

**Issue by xavierle** [rockstor/rockstor-core#749] opened 2015-07-16 17:15 UTC
following issue #742 for which the advices worked

now i cannot access any of my pools

it always shows this error : 

Error!
invalid literal for int() with base 10: 'after'

i cannot go to the page from balance and scrub

**Comment by gkadillak** [comment] 2015-07-18 16:47
Can you post what the logs display. Just run <code>tail /opt/rockstor/var/logs/rockstor.log</code>

**Comment by phillxnet** [comment] 2015-07-21 16:27
This could be a duplicate of #752 which has more information; including log snippets. #752 is derived from a forum post Entitled "Error when clicking on pool" see http://forum.rockstor.com/t/error-when-clicking-on-pool/225

**Comment by phillxnet** [comment] 2015-07-22 10:00
linking to #720 as same error.

**Comment by schakrava** [comment] 2015-07-23 19:12
Thanks @phillxnet closing as it is indeed a duplicate. #720 has the critical label, so it's high priority. Thanks for your patience.

**Closed by schakrava** 2015-07-23 19:12 UTC
Labels: duplicate
