### ISSUE TITLE
Error Starting Services: NTPD

### ISSUE THREAD

**Issue by djeraseit** [rockstor/rockstor-core#1040] opened 2015-12-02 15:39 UTC
When trying to activate NTPd in services. Although it shouldn't be relevant, maybe I should first get the disks/shares setup?

Error!

Unknown internal error doing a POST to /api/sm/services/ntpd/start

**Comment by phillxnet** [comment] 2015-12-02 19:28
@djeraseit What version of Rockstor do you see this behaviour on, I have tested here with testing 3.8-9.07 with both a local ntp server via ip address and with a "real" internet ntp server: 0.uk.pool.ntp.org
Thanks for including the info re disks/shares but you are right that this shouldn't have any effect.

What are the steps that you took to reproduce this and can it be reproduced on the testing channel.
I take it that you did first configure the service via the spanner icon. If not then we definitely want to improve that message.

Thanks for reporting.

**Comment by djeraseit** [comment] 2015-12-02 20:32
@phillxnet I had to remove the kickstart line because my hard drive on my VPS provider is not sda. I'm using the version downloaded from the website. Didn't do any configuration to the NTP just tried to enable.

It could be a fluke on my end because I did not initially disable SELINUX.

I may have to reinstall the system as I now have a broken dashboard and will update this issue accordingly.

**Comment by schakrava** [comment] 2015-12-10 17:55
@djeraseit Thanks for reporting this issue. Please don't forget to include relevant sections of the logs(/opt/rockstor/var/log) or e-mail them to support@rockstor.com right from the UI when see the error.

**Comment by phillxnet** [comment] 2016-01-17 12:07
@djeraseit I am assuming you are now OK as we haven't heard anything. I have re-tested the NTP service on 3.8-10.17, again for both local and internet NTP servers and all seem to be OK. It is however necessary to first configure the service via the spanner button and be sure to "Submit" the results. I expect that this or the SELinux (which Rockstor doesn't currently support, though we hope to in the future) was the cause of your problem. If you still have his same issue please re-open if you find it closed.

@schakrava Given the above I propose we close this issue.

**Comment by schakrava** [comment] 2016-02-24 00:48
I just like to add that the original error reported occurs when the server side operation continues to run while the nginx reverse proxy times out. This is a more generic pattern and we should improve the frontend error messaging.

Let's keep it open until we fix the messaging for this pattern of error.

**Comment by FroggyFlox** [comment] 2024-07-22 00:09
Closing this issue as it is now very old and pertains to a now legacy version of Rockstor on a different OS base.

**Closed by FroggyFlox** 2024-07-22 00:09 UTC
Labels: bug
