### ISSUE TITLE
Editing a share fails

### ISSUE THREAD

**Issue by ChristianKueppers** [rockstor/rockstor-core#1217] opened 2016-03-16 20:06 UTC
error is 
"Error!
'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
If you need more help on this issue, email us at support@rockstor.com with the following information:

```
The error message: "'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)"
A step by step description of the actions leading up to the error.
Download the tarred and zipped server logs by clicking here, and attach it to the email.
```

"

**Comment by schakrava** [comment] 2016-03-19 18:57
Thanks for reporting this, but I couldn't reproduce it. Are you able to reproduce the error consistently? If so, please list the steps.

**Comment by MedourMehdi** [comment] 2016-03-22 09:33
Hi,
We have experienced the same issue.
The reason is because you have an "é" character in logins name list.

To fix it we've proceed as follow:

in /opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/fields.py
add

`import sys`

and replace

`    def to_representation(self, value):
        return six.text_type(value)`

by

`    def to_representation(self, value):
        reload(sys)
        sys.setdefaultencoding('utf8')
        return six.text_type(value)`

**Comment by ChristianKueppers** [comment] 2016-03-25 13:23
hi, thx.
But i have´nt a special character in my passwd file. Within the domain as well not.
Christian

**Comment by osnet** [comment] 2016-05-27 17:16
same here ...
i got this after joining an AD domain with GERMAN based cn values 
i.e. Domänen-Gäste   ( domain-guests )

now i cant edit  shares or display groups

(v 3.8-13 // Linux: 4.4.5-1.el7.elrepo.x86_64)

**Comment by Hooverdan96** [comment] 2023-12-15 23:54
@phillxnet do you believe this is still an issue with all the changes into 4.x and the ongoing ones into 5.x? If not, let's close this issue.

**Closed** 2023-12-16 13:15 UTC
Labels: question
