### ISSUE TITLE
rockstor-bootstrap.service failed

### ISSUE THREAD

**Issue by bitchecker** [rockstor/rockstor-core#1054] opened 2015-12-15 13:46 UTC
When i boot Rockstor i get an error on rockstor-bootstra.service.
this is the error:

```
[root@rockstor ~]# systemctl status rockstor-bootstrap.service 
● rockstor-bootstrap.service - Rockstor bootstrapping tasks
   Loaded: loaded (/etc/systemd/system/rockstor-bootstrap.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since mar 2015-12-15 14:21:57 CET; 22min ago
 Main PID: 2233 (code=exited, status=203/EXEC)

dic 15 14:21:57 rockstor systemd[1]: Starting Rockstor bootstrapping tasks...
dic 15 14:21:57 rockstor systemd[2233]: Failed at step EXEC spawning /opt/rockstor/bin/bootstrap: No such file or directory
dic 15 14:21:57 rockstor systemd[1]: rockstor-bootstrap.service: main process exited, code=exited, status=203/EXEC
dic 15 14:21:57 rockstor systemd[1]: Failed to start Rockstor bootstrapping tasks.
dic 15 14:21:57 rockstor systemd[1]: Unit rockstor-bootstrap.service entered failed state.
dic 15 14:21:57 rockstor systemd[1]: rockstor-bootstrap.service failed.
dic 15 14:24:03 rockstor systemd[1]: Stopped Rockstor bootstrapping tasks.
```

at the moment a've masked the service for speedup boot time.

**Comment by phillxnet** [comment] 2015-12-15 14:26
@bitchecker Thanks for reporting this. Can you confirm that the file /opt/rockstor/bin/bootstrap exists?
What version of Rockstor are you on and which channel, ie stable or testing.
Also how did you install / upgrade it.
We have just had a new release and I'm afraid there have been some teething issue.

**Comment by bitchecker** [comment] 2015-12-15 14:33
@phillxnet as you can see from my previous post, file bootstrap doesn't exists.

i'm running:
```
Linux rockstor 4.2.5-1.el7.elrepo.x86_64 #1 SMP Tue Oct 27 12:32:38 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

as i've replyed you on https://github.com/rockstor/rockstor-core/issues/1053, i think (and hope) i'm running stable channel. there's a way to check channel?

**Comment by phillxnet** [comment] 2015-12-15 15:01
@bitchecker If that is in fact the case then we have the problem cause resolved. Could you answer my previous questions as this may help to pin down why and where this happened. 
ie Did you install from the iso that was released yesterday (Rockstor-3.8-10.iso) or did you install from a previously released one.

This way we can pin down where the problem lies, ie in the iso or in an also recent rpm via the update.

Thanks for chipping in on this one and sorry for the inconvenience.

**Comment by bitchecker** [comment] 2015-12-15 15:29
i've installed it today from the latest iso that i've downloaded from https://rockstor.com

**Comment by phillxnet** [comment] 2015-12-15 15:37
@bitchecker Thanks and was the file named "Rockstor-3.8-10.iso" Cheers. I have to ask as only in the last few hours was the bittorrent feed updated to be in sync with the also only recently updated source-forge feed.

You have rather caught things right on the cusp I'm afraid.

**Comment by schakrava** [comment] 2015-12-15 19:27
@bitchecker I've confirmed( again) that the latest ISO file(3.8-10) is good and installs successfully. Now, it's expected that rockstor-bootstrap service fails on first boot and prior to initial setup. After the setup, you can either manually restart it or reboot -- both of which are not necessary, but you can, to confirm all is ok.

The error you got, however, is not expected. Perhaps you should just try installing again.

Thanks @phillxnet for also confirming successful install.

**Comment by bitchecker** [comment] 2015-12-15 20:42
@schakrava i've configure the server!
i've created disk pool and shares but every reboot i see the same error on rockstar-bootstrap!

i also see that WebUI says me that i'm running kernel not supported (4.2.5) and that when i'll reboot system will startup with "new" kernel (4.2.2)....i think that there's anything that doesn't works properly!

**Comment by schakrava** [comment] 2015-12-15 22:14
The fact that it's telling you 4.2.2 is default means that you are not running the latest 3.8-10 version.

What's the output of this command: "rpm -qi rockstor"?

**Comment by bitchecker** [comment] 2015-12-16 08:37
@schakrava i've downloaded it from torrent yesterday and installed...i downloaded from sourceforge and iso is different!
I'll re-install it again with new iso, if it works without errors, i'll close issue! :-)

**Comment by bitchecker** [comment] 2015-12-16 11:16
** UPDATE **
@schakrava i've installed 3.8-10 iso and update it, so:
1) my uname says:
```
Linux Rockstor 4.2.5-1.el7.elrepo.x86_64 #1 SMP Tue Oct 27 12:32:38 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

2) my versioni of rockstor package is:
```
rockstor-3.8-8.x86_64
```

3) i still see the same error on rockstor-bootstrap.service, in fact, if i run:
```
systemctl status rockstor-bootstrap.service
```
i see:
```
● rockstor-bootstrap.service - Rockstor bootstrapping tasks
   Loaded: loaded (/etc/systemd/system/rockstor-bootstrap.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since mer 2015-12-16 12:07:38 CET; 4min 49s ago
  Process: 1947 ExecStart=/opt/rockstor/bin/bootstrap (code=exited, status=203/EXEC)
 Main PID: 1947 (code=exited, status=203/EXEC)

dic 16 12:07:38 Rockstor systemd[1]: Starting Rockstor bootstrapping tasks...
dic 16 12:07:38 Rockstor systemd[1]: rockstor-bootstrap.service: main process exited, code=exited, status=203/EXEC
dic 16 12:07:38 Rockstor systemd[1]: Failed to start Rockstor bootstrapping tasks.
dic 16 12:07:38 Rockstor systemd[1]: Unit rockstor-bootstrap.service entered failed state.
dic 16 12:07:38 Rockstor systemd[1]: rockstor-bootstrap.service failed.
```
if i check logs, i see:
```
dic 16 12:07:38 Rockstor systemd[1947]: Failed at step EXEC spawning /opt/rockstor/bin/bootstrap: No such file or directory
```
if i run:
```
ls -l /opt/rockstor/bin/
```
i see:
```
rwxr-xr-x 1 root root     1635  4 ott 01.27 backup-plugin
-rwxr-xr-x 1 root root      380  4 ott 01.24 buildout
-rwxr-xr-x 1 root root      489  4 ott 01.27 buildout-source-release
-rwxr-xr-x 1 root root     1635  4 ott 01.27 coverage
-rwxr-xr-x 1 root root     1635  4 ott 01.27 coverage2
-rwxr-xr-x 1 root root     1635  4 ott 01.27 coverage-2.7
-rwxr-xr-x 1 root root     1659  4 ott 01.27 data-collector
-rwxr-xr-x 1 root root     1647  4 ott 01.27 delete-api-key
-rwxr-xr-x 1 root root     1370 16 dic 11.51 django
-rwxr-xr-x 1 root root     1653  4 ott 01.27 django-admin.py
-rw-r--r-- 1 root root 21599668 10 set 21.12 docker
-rwxr-xr-x 1 root root     1647  4 ott 01.27 docker-wrapper
-rwxr-xr-x 1 root root     1641  4 ott 01.27 echo_supervisord_conf
-rwxr-xr-x 1 root root     1647  4 ott 01.27 flash-optimize
-rwxr-xr-x 1 root root     1597  4 ott 01.27 gunicorn
-rwxr-xr-x 1 root root     1601  4 ott 01.27 gunicorn_django
-rwxr-xr-x 1 root root     1601  4 ott 01.27 gunicorn_paster
-rwxr-xr-x 1 root root     1635  4 ott 01.27 initrock
-rwxr-xr-x 1 root root     1633  4 ott 01.27 mgmt_ip
-rwxr-xr-x 1 root root     1643  4 ott 01.27 ovpn-client-gen
-rwxr-xr-x 1 root root     1648  4 ott 01.27 ovpn-client-print
-rwxr-xr-x 1 root root     1640  4 ott 01.27 ovpn-initpki
-rwxr-xr-x 1 root root     1641  4 ott 01.27 pidproxy
-rwxr-xr-x 1 root root     1633  4 ott 01.27 prep_db
-rwxr-xr-x 1 root root     1633  4 ott 01.27 pwreset
-rwxr-xr-x 1 root root     1643  4 ott 01.27 qgroup-clean
-rwxr-xr-x 1 root root     1657  4 ott 01.27 qgroup-maxout-limit
-rwxr-xr-x 1 root root     1627  4 ott 01.27 rcli
-rwxr-xr-x 1 root root     1673  4 ott 01.27 replicad
-rwxr-xr-x 1 root root     1641  4 ott 01.27 rockon-json
-rwxr-xr-x 1 root root     1637  4 ott 01.27 sm
-rwxr-xr-x 1 root root     1671  4 ott 01.27 st-pool-scrub
-rwxr-xr-x 1 root root     1667  4 ott 01.27 st-snapshot
-rwxr-xr-x 1 root root     1651  4 ott 01.27 supervisorctl
-rwxr-xr-x 1 root root     1647  4 ott 01.27 supervisord
-rwxr-xr-x 1 root root     1839  4 ott 01.27 test
```

**Comment by phillxnet** [comment] 2015-12-16 14:51
@bitchecker Thanks for all the info. It looks like you have already hit on the problem with your other reported issue #1056 as your rockstor rpm version has been severely downgraded some how, presumably as you indicate in issue #1056 by the *yum distro-sync* command.
As one would expect a clean install of Rockstor 3.8-10 has the following rockstor package info.
```
yum info rockstor
Loaded plugins: changelog, fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.sov.uk.goscomb.net
 * epel: www.mirrorservice.org
 * extras: www.mirrorservice.org
 * updates: mirror.sov.uk.goscomb.net
Installed Packages
Name        : rockstor
Arch        : x86_64
Version     : 3.8
Release     : 10
Size        : 107 M
Repo        : installed
From repo   : anaconda
Summary     : RockStor -- Store Smartly
Licence     : GPL
Description : RockStor -- Store Smartly
```
Noting here for the time being to link the issues.

**Comment by bitchecker** [comment] 2016-02-15 10:25
any updates?

**Comment by schakrava** [comment] 2016-02-15 23:48
Looks like in your case bootstrap failed because package was downgraded by running distro-sync. We don't expect users to run distro-sync. Is that a common practice? If so, why?

**Comment by bitchecker** [comment] 2016-02-16 08:31
because when you install a server, you update all packages usually!

**Comment by phillxnet** [comment] 2016-02-16 10:10
@bitchecker Am I right in assuming that this only happens if you don't first select an updates channel such as is prompted on first login and via System - Software Update as distro-sync is not an upgrade tool but a sync tool so is fully expected to downgrade packages if repo's have older versions. Until the update channel is selected you are not yet setup for updates, at least from Rockstor. Also if Rockstor includes a newer package that is in one of the yet to be selected channels (and on the iso installer) and you distro-sync before one of those repos is configured then it will also be downgraded to what the upstream repos offer. If the default ie non testing and non stable repo is to have a newer version of the Rockstor package to account for distro-sync, which is not run by the appliance itself, which version would it be.

Of course I may have this all wrong.

**Comment by agabrys** [comment] 2016-10-23 19:51
Hi,
I had the same problem. @sfranzen wrote many tips "how to solve this problem" in #1066.

I solved it by:
* execute `/opt/rockstor/bin/initrock`
* add `cliapp` at `Web GUI → System → Access Keys`
* execute `systemctl start rockstor-bootstrap`
* execute `systemctl start smb`

I also rebooted server and it launched all services correctly 😄 
I hope it will solve your problem too.

**Comment by sfranzen** [comment] 2016-10-24 10:25
@agabrys Meh, this unpredictable bug is still rearing its head now and then. Glad you found the way to my ugly hack out of it, but do you remember doing anything special/unusual on the rockstor right before this was triggered? I still would rather solve this bug permanently.

**Comment by agabrys** [comment] 2016-10-25 19:03
@sfranzen I tried to reproduce the problem for 2 hours, but unfortunately I cannot 😞

**Comment by rayfoss** [comment] 2019-04-18 20:36
I triggered the bug somehow. I am on 3.9.2-48 stable.

I recall disabling afp, nfs services, changing smb config, deleting a Share, and then creating a new share with a different name.

Computers wouldn't connect for some reason, socket error. But rockstor would still ping. Upon restart the drives were unmounted which is what led me here.

**Comment by FroggyFlox** [comment] 2024-07-11 21:01
Closing this issue as it is now pertaining to a legacy OS base.

**Closed by FroggyFlox** 2024-07-11 21:01 UTC
