### ISSUE TITLE
convey pool balance status properly on the web-ui

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#862] opened 2015-09-06 13:57 UTC
After a pool balance(triggered by resize), the balance may not have actually balanced fully. 
1. This information needs to be conveyed properly in the UI. 
2. User should not be able to do another resize if the balance is underway. 
3. To the extent possible, backend should auto correct the problem.
4. If manual intervention is required, appropriate help text should be provided on the UI.

http://forum.rockstor.com/t/raid-is-not-created/428

**Comment by MFlyer** [comment] 2016-10-18 12:52
@phillxnet & @schakrava : what about this issue after #1444 and #1445 by Phil?? Can we close it?
M.

**Comment by phillxnet** [comment] 2016-10-18 13:51
@MFlyer my #1444 was only related to unit testing but did add tests for backend reporting of balance state. #1445 improved the real time / mid progress reporting of balance (at least after a page refresh) but had no effect on 1, 2, 3, or 4 in above. I think this one is more related to sanity state reporting rather than progress reporting which was what I marginally improved with #1445.

Though I do think the title of this issue could be more reflective of it's details, or it could be separated out into multiple issues maybe.
Ie first sentence and most (1) could be addressed by showing (in a detail area) a greater breakdown of the pool data, metadata etc and the proportion of which reflects the abstracted raid1, raid10, etc state as sometimes chunks can fail to be converted. Extracting this info would then allow analysis of conversion state; with maybe a suggestion to re-balance if it is in question and their isn't a current balance in progress.

I think from memory 2. is already sorted. Needs testing again.

**Comment by sfranzen** [comment] 2016-10-18 15:53
I'm not entirely sure how the balance status is currently reported, but I know it is possible to write something like this:
```
setInterval(function() {
  // retrieve/update balance progress
  if (balanceDone)
    clearInterval();
}, 1000);
```
This snippet could be used to automatically update a progress bar element, which could just be inside the existing balance table.

**Comment by phillxnet** [comment] 2023-03-23 16:56
Closing as likely resolved give our recent work in this area. Most specifically our Web-UI surfacing of what we reference as internal balances (i.e. those caused by disk removal that are not ameanable to btrfs balance status reprots).
We also have some very recent improvements on cli initiated balance awareness.

**Closed by phillxnet** 2023-03-23 16:56 UTC
Labels: enhancement, Critical
