### ISSUE TITLE
Rockstor install; no HDD / SSD detected

### ISSUE THREAD

**Issue by ManuelBachmann** [rockstor/rockstor-core#2149] opened 2020-03-29 12:39 UTC
When i try to install Rockstor, in the GUI no HDD/SSD can be detected, and i cant figure out why. Any ideas?

**Comment by phillxnet** [comment] 2020-03-29 14:24
@ManuelBachmann First off, welcome; but GitHub issues is not really the place for a support question such as this.

I would like to invite you to ask the same question, along with some information about your hardware setup, at our community forum:

https://forum.rockstor.com/

All current Rockstor developers are also forum members. Plus many other community members may have ideas on why you drive is not showing up. But do remember to put in hardware information. Also could you specify in this forum post if this is happening during the installer GUI or Rockstor's Web-UI. That will help folks help you. You can also include pics etc if that helps to clarify the issue.

Closing this GitHub issue as 'moved to forum' for now at least. We can always re-open if we find a reproducer / suspected cause etc.

Thanks for reporting your findings and hopefully the reason this is happening can be resolved on the forum, unless it's identified as a bug of course.

**Closed by phillxnet** 2020-03-29 14:24 UTC
