### ISSUE TITLE
Error while replicating - Rockstor 3.9.2-57

### ISSUE THREAD

**Issue by PiotrSzalach** [rockstor/rockstor-core#2172] opened 2020-05-20 16:12 UTC
I'm trying to do replication between 2 instances. Both running 3.9.2-57

I get error. 
[20/May/2020 11:02:01] ERROR [smart_manager.replication.sender:73] Id: CED72042-4E20-A540-0B52-011A4CE58E9C-2. Failed to create snapshot: STORAGE_2_replication_1. Aborting.. Exception: [u'Invalid api end point: http://127.0.0.1:8000/api/shares/STORAGE/snapshots/STORAGE_2_replication_1']

**Comment by phillxnet** [comment] 2020-05-20 21:17
@PiotrSzalach Thanks for the report.

Can you start a thread detailing your finding on our forum, but first read the rest of this text as I had an idea later that matches your quoted errror:
https://forum.rockstor.com/
Then hopefully we can narrow down if all is setup correctly and get a reproducer for this issue.
I'm due to look at replication again soon so this may help.
Also we have an ongoing thread, which is likely unrelated, but does have some setup info that may have been missed. Take a look at this thread:

https://forum.rockstor.com/t/replication-start-and-then-failes/7048

Specifically the bit about the spanner setting on the Replication service to select the network interface. Our docs are poor in this area currently.

I think your issue is different but that thread has some setup info.

We can leave this issue open to return to it once we have a reproducer if it turns our to be an existing bug. Also take a look at this forum thread to make sure you are actually running 3.9.2-57 as your quoted error of:

> [u'Invalid api end point: http://127.0.0.1:8000/api/shares/STORAGE/snapshots/STORAGE_2_replication_1']

Looks more like one we might have seen from 3.9.1-16 last CentOS based testing release. We had a bug where testing to stable didn't 'take' but shows as installed in the Web-UI. This thread show how you can tell if your systems are affected and the one-off work-around:

https://forum.rockstor.com/t/to-all-stable-channel-subscribers/6617

if you were affected by this then 'fake' update from last CentOS based testing to stable then it's probably best you wipe your existing replication config at both ends and start over as much has changed in the interim 2 years or so.

Hope that helps, and take a look at the second thread first to make sure you are running the latest stable as last CentOS based testing was known to have broken replication and your api endpoint error looks very much like that issue to me initially as we changed the api in the interim. I.e. we use to use share names and moved to share id's. Your api endpoint is using a name name not a number. Should be a numeric where the first "STORAGE" is hence the suspicion of a 'fake' display in the Web-UI of the actual version you are running. That second forum thread is a good guide to sort it.

Apologies for the ramble of a reply, it's now quite late in UK but wanted to give you some pointers.

**Comment by Hooverdan96** [comment] 2023-12-16 02:03
@phillxnet, since we're now in 4.x and quickly progressing towards 5.x this probably needs to be re-evaluated in a new issue, since the entire underlying setup has changed? If you agree, let's close this one, especially since you're already working on replication failure, which will hopefully then be tested by the community to surface additional/any other issues that will occur.

**Comment by phillxnet** [comment] 2023-12-16 13:51
@Hooverdan96 Thanks for yet more Issue Triage, much apprecaited.

> If you agree, let's close this one

Yes I agree, I'm pretty sure this particular issue was fixed way back and as you say we have many moving parts in the interim.

**Closed by phillxnet** 2023-12-16 13:51 UTC
