### ISSUE TITLE
Network config:  Failed to configure network interface(X) due to a system error 

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#915] opened 2015-10-01 19:55 UTC
If you have multiple network devices, and you edit one that is not in use, you get the following error:

    Network config:  Failed to configure network interface(X) due to a system error 

Also would it be possible to set the type to "None" if you never want the interface to come up? Like for wireless for example.

**Comment by schakrava** [comment] 2015-10-05 00:54
@roweryan Thanks for opening this issue, but could you retest with 3.8-8 and report back what you see? I think this should be fixed now.

**Comment by roweryan** [comment] 2015-10-05 05:10
When I abandon configuring a new interface by clicking Cancel I get:

    Error! execv() arg 2 must contain only strings

**Comment by roweryan** [comment] 2015-10-05 05:11
Also the "none" type is missing.

**Comment by schakrava** [comment] 2015-10-08 18:23
@roweryan with the info provided here, I am unable to reproduce the behavior. Are you able to consistently reproduce it? If so, please detail the steps and send the logs to support@rockstor.com

**Comment by roweryan** [comment] 2015-10-08 20:39
go to settings > network interfaces
click actions > pencil (edit) next to a device you do not use
click cancel

```
Error!

execv() arg 2 must contain only strings

[08/Oct/2015 22:28:00] ERROR [storageadmin.util:38] request path: /api/network/enp0s31f6 method: PUT data: {u'dns_servers': u'', u'itype': u'', u'name': u'enp0s31f6', u'ipaddr': u'', u'method': u'manual', u'netmask': u'', u'gateway': u''}
[08/Oct/2015 22:28:00] ERROR [storageadmin.util:39] exception: execv() arg 2 must contain only strings
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 40, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/network.py", line 192, in put
    gateway=gateway, dns_servers=dns_servers)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 219, in config_network_device
    run_command(add_cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 71, in run_command
    p = subprocess.Popen(cmd, shell=shell, stdout=stdout, stderr=stderr)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

**Comment by schakrava** [comment] 2015-10-09 00:38
Figured it out @roweryan . You are not using Chrome browser are you? I am guessing Firefox, but for UI related issues, please include your browser going forward. Anyway, fix is on the way. Really appreciate the bug report!

**Closed** 2015-10-09 00:39 UTC
Labels: question

**Comment by roweryan** [comment] 2015-10-09 05:21
I use Firefox - thanks!

**Comment by roweryan** [comment] 2015-10-10 15:57
It works great, thanks!
