### ISSUE TITLE
Scheduled snapshot failure?

### ISSUE THREAD

**Issue by carlbeech** [rockstor/rockstor-core#2048] opened 2019-05-25 04:13 UTC
Hi

I'd suspected that I had an issue with scheduled snapshots, however, I wasn't sure of the details until I got email output working...  I received this morning:

Traceback (most recent call last):
  File "/opt/rockstor/bin/st-snapshot", line 45, in <module>
    sys.exit(scripts.scheduled_tasks.snapshot.main())
  File "/opt/rockstor/src/rockstor/scripts/scheduled_tasks/snapshot.py", line 95, in main
    validate_snap_meta(meta)
  File "/opt/rockstor/src/rockstor/scripts/scheduled_tasks/snapshot.py", line 39, in validate_snap_meta
    if meta['share'].isdigit():
AttributeError: 'int' object has no attribute 'isdigit'

Couple of items:
* Firstly, the email doesn't say which snapshot task has the issue - I have a snapshot task for each share
* I've managed (I think) to work out the share - it has been working and I had daily snapshots working fine, from 6 May but stopped on 12 May - the task history says 'error' but I don't know how to get to the error details (I'm assuming the problem is as above?)

Logging in as SSH, and assuming I'm in the correct location, the files are:

[root@rockstor_home PicturesData]# ls -al
total 16
drwxrwxr-x 1 carl carl 338 May 24 03:00 .
drwxr-xr-x 1 root root  44 May  4 17:40 ..
drwxr-xr-x 1 root carl 502 May  5 04:29 PICTURES
drwxr-xr-x 1 root root   0 May  6 01:01 .SNAPSHOT__201905050600
drwxr-xr-x 1 root root   0 May  7 01:00 .SNAPSHOT__201905060600
drwxr-xr-x 1 root root   0 May  8 01:01 .SNAPSHOT__201905070600
drwxr-xr-x 1 root root   0 May  9 01:00 .SNAPSHOT__201905080600
drwxr-xr-x 1 root root   0 May 10 01:00 .SNAPSHOT__201905090600
drwxr-xr-x 1 root root   0 May 11 01:00 .SNAPSHOT__201905100600
drwxr-xr-x 1 root root   0 May 24 03:00 .SNAPSHOT__201905240300
[root@rockstor_home PicturesData]# pwd
/mnt2/Pictures/PicturesData

Are there any log files I can examine - or is the data at fault in the Rockstor database?

Cheers

Carl.

PS: If I delete the scheduled task...
* will the snapshots be deleted as well, or do I need to manually delete them through the GUI
* if I immediately re-create the task using the same parameters, will the snapshots created by the 'old' snapshot task be adopted by the new snapshot task?  (hope that makes sense...)

**Comment by phillxnet** [comment] 2019-05-25 14:56
@carlbeech Thanks for the report, although this may have been better located on the forum but I can answer some of your questions quickly:
Logs:
```
/opt/rockstor/var/log/rockstor.log
```
and regular system logs via:
```
journalctl
```
You may have been affected by an older issue were a Rockstor update broke some scheduled tasks. But given it only affected this one that seems unlikely. Assuming you have others like it. In that case a scheduled task delete / recreate sorted things out.

It's safe to delete the scheduled task, it only removes the database info entry and cron triggers for the associated task.
I'm uncertain of the association mechanism of snapshot task to snapshots taken by that task: I haven't looked at that code for a bit. But you can easily do a trial run on another share to find out.

Again a question such as this is better asked on the forum where it will receive more eyes. We try to keep the GitHub issues to those that are as tightly defined as possible and hopefully with reproducers included. That way we can reproduce and hopefully track / fix the cause.

See how you get on with that delete and recreate once you've experimented with non critical history. But in any case the snapshots will still be visible as snapshots against the associated share.

Hope that helps.
Also forum is to be found at: https://forum.rockstor.com/
and there are likely a few who have run into this. Although the older issue I mentioned was quite some time ago now.

**Comment by carlbeech** [comment] 2019-05-26 02:27
Hi
Apologies - I thought github was the place to raise issues because that's where the web page pointed me to when the system encountered an error - no worries - I'll delete and re-create and see how things go on - if there's any issues or I spot something in the logs, I'll raise a new item in the forum...

Many thanks

Carl.

**Comment by Hooverdan96** [comment] 2023-12-15 22:33
@phillxnet, @carlbeech, I don't remember seeing an issue raised in the forum on this again recently (since we've been on 4.x for a while). Can we close this?

**Comment by phillxnet** [comment] 2023-12-16 11:34
@Hooverdan96 @carlbeech Lets close this as we have had years of development in this area in the interim. A fresh issue against latest code with reproducer is the goal here areally.

**Closed by phillxnet** 2023-12-16 11:34 UTC
