### ISSUE TITLE
Plex: Configuration of additional storage not shown

### ISSUE THREAD

**Issue by maxhq** [rockstor/rockstor-core#976] opened 2015-10-21 23:38 UTC
Steps to reproduce:
- set up Plex
- edit Plex Settings (tool icon in Rockstor)
- add a second storage share
- save configuration (needs my fix #975)
- Plex starts automatically
- stop Plex
- go to Plex Settings

Now the newly added storage is not visible anymore.

**EDIT**: Obviously the actual configuration file (`/mnt2/rockstor_addons/containers/39..55/config.json`) still contains the additional storage / mounts. Only the web UI does not show it anymore. I wonder if adding a third storage would then delete the second one.

**Comment by schakrava** [comment] 2015-12-12 03:18
Thanks for filing this issue @maxhq. Now that 3.8-10 is out, I am moving to Rock-on improvements. I'll take a look

**Comment by schakrava** [comment] 2015-12-27 21:12
@maxhq Finally, I got around to reproducing this issue. However, I could not. I've installed Plex, with the two required Shares and then added a third one, pretty much following steps you've outlined(thanks!). The new Share is reflected in the ui. In the below image, newmovies is the third share I added. Am I missing something here?

![plex_settings](https://cloud.githubusercontent.com/assets/1123552/12012008/191e1be2-ac9b-11e5-8d7d-258a8535c784.png)

**Comment by schakrava** [comment] 2016-01-07 04:22
Closing the issue as I still cannot reproduce it.

**Closed by schakrava** 2016-01-07 04:22 UTC
Labels: question

**Comment by oivanenko** [comment] 2016-02-08 20:38
Hi, Suman!

I have exactly the same issue with Plex rock-on. I had added main storage and three additional storages to Plex rock-on and now Plex actually "see" all storages, but "Plex settings" shows only main storage. Is it possible, that such kind of issue appears when already used by other rock-on (for Transmission rock-on in my case) share been additionally added to Plex?

[config.json.txt](https://github.com/rockstor/rockstor-core/files/122163/config.json.txt)
![plex_really_available_shares](https://cloud.githubusercontent.com/assets/201648/12898242/c2996b34-cebc-11e5-88ed-a53922b8a225.png)
![plex_settings](https://cloud.githubusercontent.com/assets/201648/12898241/c295ce70-cebc-11e5-88fa-f7acd05bfedc.png)
![shares](https://cloud.githubusercontent.com/assets/201648/12898239/c290d9d8-cebc-11e5-9ef4-a0aeee11f459.png)
![transmission_settings](https://cloud.githubusercontent.com/assets/201648/12898240/c293abea-cebc-11e5-9bec-5eb3bbf5851a.png)
