### ISSUE TITLE
Still logged in after reboot

### ISSUE THREAD

**Issue by javahaxxor** [rockstor/rockstor-core#612] opened 2015-02-25 14:09 UTC
You should invalidate the session before executing the reboot (in the logout/shutdown/reboot dialog). If not, a refresh of the page causes another reboot

**Comment by schakrava** [comment] 2015-02-26 02:21
Thanks for filing this issue!

**Comment by javahaxxor** [comment] 2015-02-28 21:45
Happy to oblige.. Maybe some day I'll even try fixing stuff like this myself ..

**Comment by schakrava** [comment] 2015-03-01 02:22
Please feel free. Pull requests are welcome.

**Comment by cron410** [comment] 2015-03-17 03:02
I just attempted to reproduce the issue and was successful. However, the session was somewhat invalidated. I was able to navigate the tabs and submenus, but none of the actual content was able to load. I would also like to test whether I am able to reboot or shutdown the appliance i this state. This may be a symptom of issue #624 where certain background services are still starting. That may be causing the issues with loading the actual pages within each menu.

**Comment by cron410** [comment] 2015-03-17 03:08
just tested again. Still completely logged in after a reboot. Background services seemed to start faster this time and I did not experience any blank pages when navigating menus.

**Comment by javahaxxor** [comment] 2015-03-17 09:19
if you reboot the machine and keep the browser tab open, refreshing it after a couple of minutes (when the server has restarted) will restart the server again

**Comment by cron410** [comment] 2015-03-17 12:28
Very bad behavior indeed. The reboot page should probably redirect to a non-functionaly information page that will redirect to the login screen after 3-5 minutes. We can use my test ESXi server as reference for the slowest machine. Its running 3 VMs on a 5400rpm laptop drive!

**Comment by javahaxxor** [comment] 2015-03-17 12:33
hehe that's a lot to demand from a laptop drive, especially with that high I/O ..
![rockstor](https://cloud.githubusercontent.com/assets/3932029/6687308/33f1cb3e-ccaa-11e4-81fe-ca802cb2d16e.png)

**Comment by schakrava** [comment] 2015-03-17 17:04
@javahaxxor and @cron410 Thanks for adding more feedback. Certainly helpful!

**Comment by kamal-gade** [comment] 2015-03-27 16:17
I am able to reproduce this issue. The browser session seems to be still active after reboot. We have to invalidate the session before reboot.

**Comment by javahaxxor** [comment] 2015-03-27 16:30
Just set the cookie date to zero, the browser will remove it

**Comment by schakrava** [comment] 2015-04-20 23:20
this is closed by #627

**Closed by schakrava** 2015-04-20 23:20 UTC
Labels: bug
